-- =============================================================================
-- AIRLINE OPERATION SUITE (AOS) DATABASE SCHEMA AND PL/SQL STORED PROCEDURES
-- Database Target: Oracle Database 12c / 19c / 21c / 23c
-- =============================================================================

-- =============================================================================
-- 1. TABLE CREATION
-- =============================================================================

CREATE TABLE AIRLINE_USER_MSTR_TBL (
	USER_ID       NUMBER(10),
	USERNAME      VARCHAR2(50) NOT NULL,
	MOBILENO      NUMBER(10) CONSTRAINT MOBILENO_CHK CHECK(LENGTH(MOBILENO)=10),
	PASSWD        VARCHAR2(100) NOT NULL,
	MPIN          NUMBER(4),
	OTP           NUMBER(6),
	PASSPORT_IMG  VARCHAR2(2000),
	IS_ACTIVE     CHAR(1) DEFAULT 'Y',
	CREATED_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP,
	CREATED_BY    VARCHAR2(10),
	UPDATED_TIME  TIMESTAMP,
	UPDATED_BY    VARCHAR2(10),
	CREATED_IP    VARCHAR2(100),
	UPDATED_IP    VARCHAR2(100),      
	CONSTRAINT PK_USER_ID PRIMARY KEY (USER_ID),
	CONSTRAINT UK_MOBILENO UNIQUE (MOBILENO),
	CONSTRAINT UK_USERNAME UNIQUE (USERNAME)      
);
/

CREATE TABLE AIRLINE_ROLE_MSTR_TBL (
	ROLE_ID       NUMBER(10),
	ROLE_NAME     VARCHAR2(100) NOT NULL,
	IS_ACTIVE     CHAR(1) DEFAULT 'Y',
	CREATED_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP,
	CREATED_BY    VARCHAR2(10),
	UPDATED_TIME  TIMESTAMP,
	UPDATED_BY    VARCHAR2(10),
	CREATED_IP    VARCHAR2(100),
	UPDATED_IP    VARCHAR2(100),
	CONSTRAINT PK_ROLE_ID PRIMARY KEY (ROLE_ID)
);
/

CREATE TABLE AIRLINE_USER_ROLE_MAP_TBL (
	ROW_NO        NUMBER(35) GENERATED ALWAYS AS IDENTITY,
	USER_ID       NUMBER(10),
	ROLE_ID       NUMBER(10),
	IS_ACTIVE     CHAR(1) DEFAULT 'Y',
	CREATED_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP,
	CREATED_BY    VARCHAR2(10),
	UPDATED_TIME  TIMESTAMP,
	UPDATED_BY    VARCHAR2(10),
	CREATED_IP    VARCHAR2(100),
	UPDATED_IP    VARCHAR2(100),
	CONSTRAINT PK_ROW_NO PRIMARY KEY (ROW_NO),
	CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE_ID),
	CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES AIRLINE_USER_MSTR_TBL(USER_ID),
	CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES AIRLINE_ROLE_MSTR_TBL(ROLE_ID)
);
/

CREATE TABLE AIRLINE_MENU_MSTR_TBL (
	MENU_ID       NUMBER(10),
	MENU_NAME     VARCHAR2(100) NOT NULL,
	IS_ACTIVE     CHAR(1) DEFAULT 'Y',
	CREATED_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP,
	CREATED_BY    VARCHAR2(50),
	UPDATED_TIME  TIMESTAMP,
	UPDATED_BY    VARCHAR2(50),
	CREATED_IP    VARCHAR2(45),
	UPDATED_IP    VARCHAR2(45),
	CONSTRAINT PK_MENU_ID PRIMARY KEY (MENU_ID),
	CONSTRAINT CHK_MENU_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);
/

CREATE TABLE AIRLINE_CITY_MSTR_TBL (
    CITY_ID         NUMBER(10),
    CITY_NAME       VARCHAR2(100) NOT NULL,
    STATE_NAME      VARCHAR2(100),
    COUNTRY_NAME    VARCHAR2(100),
    IS_ACTIVE       CHAR(1) DEFAULT 'Y',
    CREATED_TIME    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY      VARCHAR2(10),
    UPDATED_TIME    TIMESTAMP,
    UPDATED_BY      VARCHAR2(10),
    CREATED_IP      VARCHAR2(100),
    UPDATED_IP      VARCHAR2(100),
    CONSTRAINT PK_CITY_ID PRIMARY KEY (CITY_ID)
);
/

CREATE TABLE AIRLINE_ROLE_MENU_MAP_TBL (
	ROW_NO        NUMBER(35) GENERATED ALWAYS AS IDENTITY,
	ROLE_ID       NUMBER(10),
	MENU_ID       NUMBER(10),
	IS_ACTIVE     CHAR(1) DEFAULT 'Y',
	CREATED_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP,
	CREATED_BY    VARCHAR2(10),
	UPDATED_TIME  TIMESTAMP,
	UPDATED_BY    VARCHAR2(10),
	CREATED_IP    VARCHAR2(100),
	UPDATED_IP    VARCHAR2(100),      
	CONSTRAINT AIRLINE_ROLE_MENU_MAP_TBL_PK_ROW_NO PRIMARY KEY (ROW_NO),
	CONSTRAINT AIRLINE_ROLE_MENU_MAP_TBL_UK UNIQUE (ROLE_ID, MENU_ID)
);
/

CREATE TABLE AIRLINE_AIRPORT_MSTR_TBL (
    AIRPORT_ID      NUMBER(10),
    AIRPORT_NAME    VARCHAR2(200) NOT NULL,
    AIRPORT_CODE    VARCHAR2(10) NOT NULL,
    CITY_ID         NUMBER(10),
    IS_ACTIVE       CHAR(1) DEFAULT 'Y',
    CREATED_TIME    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY      VARCHAR2(10),
    UPDATED_TIME    TIMESTAMP,
    UPDATED_BY      VARCHAR2(10),
    CREATED_IP      VARCHAR2(100),
    UPDATED_IP      VARCHAR2(100),
    CONSTRAINT PK_AIRPORT_ID PRIMARY KEY (AIRPORT_ID),
    CONSTRAINT UK_AIRPORT_CODE UNIQUE (AIRPORT_CODE),
    CONSTRAINT FK_AIRPORT_CITY FOREIGN KEY (CITY_ID) REFERENCES AIRLINE_CITY_MSTR_TBL(CITY_ID)
);
/

CREATE TABLE AIRLINE_FLIGHT_COMPANY_MSTR_TBL (
    COMPANY_ID      NUMBER(10),
    COMPANY_NAME    VARCHAR2(200) NOT NULL,
    COMPANY_CODE    VARCHAR2(20),
    IS_ACTIVE       CHAR(1) DEFAULT 'Y',
    CREATED_TIME    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY      VARCHAR2(10),
    UPDATED_TIME    TIMESTAMP,
    UPDATED_BY      VARCHAR2(10),
    CREATED_IP      VARCHAR2(100),
    UPDATED_IP      VARCHAR2(100),
    CONSTRAINT PK_COMPANY_ID PRIMARY KEY (COMPANY_ID)
);
/

CREATE TABLE AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL (
    PASSENGER_ID        NUMBER(10),
    PASSENGER_NAME      VARCHAR2(200) NOT NULL,
    GENDER              CHAR(1),
    DOB                 DATE,
    MOBILE_NO           NUMBER(10),
    EMAIL_ID            VARCHAR2(200),
    PASSPORT_NO         VARCHAR2(50),
    IS_ACTIVE           CHAR(1) DEFAULT 'Y',
    CREATED_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY          VARCHAR2(10),
    UPDATED_TIME        TIMESTAMP,
    UPDATED_BY          VARCHAR2(10),
    CREATED_IP          VARCHAR2(100),
    UPDATED_IP          VARCHAR2(100),
    CONSTRAINT PK_PASSENGER_ID PRIMARY KEY (PASSENGER_ID)
);
/

CREATE TABLE AIRLINE_FLIGHT_MSTR_TBL (
    FLIGHT_ID          NUMBER(10),
    FLIGHT_NO          VARCHAR2(20) NOT NULL,
    COMPANY_ID         NUMBER(10) NOT NULL,
    FLIGHT_NAME        VARCHAR2(100),
    IS_ACTIVE          CHAR(1) DEFAULT 'Y',
    CREATED_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY         VARCHAR2(20),
    UPDATED_TIME       TIMESTAMP,
    UPDATED_BY         VARCHAR2(20),
    CREATED_IP         VARCHAR2(100),
    UPDATED_IP         VARCHAR2(100),
    CONSTRAINT PK_FLIGHT_ID PRIMARY KEY (FLIGHT_ID),
    CONSTRAINT UK_FLIGHT_NO UNIQUE (FLIGHT_NO),
    CONSTRAINT FK_FLIGHT_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES AIRLINE_FLIGHT_COMPANY_MSTR_TBL(COMPANY_ID),
    CONSTRAINT CHK_FLIGHT_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL (
    DYNAMIC_PRICE_ID      NUMBER(10),
    FLIGHT_ID             NUMBER(10),
    SOURCE_AIRPORT_ID     NUMBER(10),
    DEST_AIRPORT_ID       NUMBER(10),
    FLIGHT_DATE           DATE,
    DEPARTURE_TIME        TIMESTAMP,
    ARRIVAL_TIME          TIMESTAMP,
    TOTAL_SEATS           NUMBER(5),
    AVAILABLE_SEATS       NUMBER(5),
    CURRENT_PRICE         NUMBER(10,2),
    IS_ACTIVE             CHAR(1) DEFAULT 'Y',
    CREATED_TIME          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY            VARCHAR2(20),
    UPDATED_TIME          TIMESTAMP,
    UPDATED_BY            VARCHAR2(20),
    CREATED_IP            VARCHAR2(100),
    UPDATED_IP            VARCHAR2(100),
    CONSTRAINT PK_DYNAMIC_PRICE_ID PRIMARY KEY (DYNAMIC_PRICE_ID),
    CONSTRAINT FK_DP_FLIGHT FOREIGN KEY (FLIGHT_ID) REFERENCES AIRLINE_FLIGHT_MSTR_TBL(FLIGHT_ID),
    CONSTRAINT FK_DP_SOURCE FOREIGN KEY (SOURCE_AIRPORT_ID) REFERENCES AIRLINE_AIRPORT_MSTR_TBL(AIRPORT_ID),
    CONSTRAINT FK_DP_DEST FOREIGN KEY (DEST_AIRPORT_ID) REFERENCES AIRLINE_AIRPORT_MSTR_TBL(AIRPORT_ID)
);
/

CREATE TABLE AIRLINE_TICKET_BOOKING_TRANSACTION_TBL (
    BOOKING_ID             NUMBER(10),
    PASSENGER_ID           NUMBER(10),
    DYNAMIC_PRICE_ID       NUMBER(10),
    PNR_NO                 VARCHAR2(20),
    SEAT_NO                VARCHAR2(10),
    BOOKING_STATUS         VARCHAR2(20),
    PAYMENT_STATUS         VARCHAR2(20),
    BOOKING_AMOUNT         NUMBER(10,2),
    BOOKING_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y',
    CREATED_TIME           TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY             VARCHAR2(20),
    UPDATED_TIME           TIMESTAMP,
    UPDATED_BY             VARCHAR2(20),
    CREATED_IP             VARCHAR2(100),
    UPDATED_IP             VARCHAR2(100),
    CONSTRAINT PK_BOOKING_ID PRIMARY KEY (BOOKING_ID),
    CONSTRAINT FK_BOOKING_PASSENGER FOREIGN KEY (PASSENGER_ID) REFERENCES AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL(PASSENGER_ID),
    CONSTRAINT FK_BOOKING_DYNAMIC_PRICE FOREIGN KEY (DYNAMIC_PRICE_ID) REFERENCES AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL(DYNAMIC_PRICE_ID),
    CONSTRAINT UK_PNR_NO UNIQUE (PNR_NO)
);
/

CREATE TABLE AIRLINE_ERROR_LOG_TBL (
    ROW_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ERROR_DESC VARCHAR2(4000),
    CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

CREATE TABLE AIRLINE_PARAMETER_LOG_TBL (
    ROW_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PARAM VARCHAR2(4000),
    CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

-- =============================================================================
-- 2. SEQUENCES
-- =============================================================================

CREATE SEQUENCE AIRLINE_USER_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 10000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_ROLE_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 11000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_MENU_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 12000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_CITY_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 13000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_AIRPORT_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 14000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_FLIGHT_COMPANY_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 15000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 16000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_PASSENGERS_REGD_FORM_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 17000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_FLIGHT_MSTR_TBL_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 18000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_TICKET_BOOKING_TRANSACTION_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 19000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

-- =============================================================================
-- 3. INITIAL SEED DATA
-- =============================================================================

INSERT INTO AIRLINE_USER_MSTR_TBL (
	USER_ID, USERNAME, MOBILENO, PASSWD, MPIN, OTP, CREATED_BY, PASSPORT_IMG
) VALUES (
	AIRLINE_USER_MSTR_SEQ.NEXTVAL, 'dushmantadas@aos.com', 7008233179, 'das@123', 1111, NULL, 'DUSHMANTA',
	'C:\SOFTWARE\AOS\frontend\static\passport\das passport.jpg'
);

INSERT INTO AIRLINE_USER_MSTR_TBL (
	USER_ID, USERNAME, MOBILENO, PASSWD, MPIN, OTP, CREATED_BY, PASSPORT_IMG
) VALUES (
	AIRLINE_USER_MSTR_SEQ.NEXTVAL, 'darshildas@aos.com', 9861017552, 'das@123', 1111, NULL, 'DARSHIL',
	'C:\SOFTWARE\AOS\frontend\static\passport\OMM_PASSPORT_PHOTO.jpeg'
);
COMMIT;

INSERT INTO AIRLINE_ROLE_MSTR_TBL (ROLE_ID, ROLE_NAME, CREATED_BY, CREATED_IP)
VALUES (AIRLINE_ROLE_MSTR_SEQ.NEXTVAL, 'ADMIN', 'DARSHIL', '100.125.49.24');

INSERT INTO AIRLINE_ROLE_MSTR_TBL (ROLE_ID, ROLE_NAME, CREATED_BY, CREATED_IP)
VALUES (AIRLINE_ROLE_MSTR_SEQ.NEXTVAL, 'OPERATOR', 'DARSHIL', '100.125.49.24');
COMMIT;

INSERT INTO AIRLINE_USER_ROLE_MAP_TBL (USER_ID, ROLE_ID, CREATED_BY, CREATED_IP)
VALUES (10000001, 11000001, 'DUSHMANTA', '100.125.49.24');  

INSERT INTO AIRLINE_USER_ROLE_MAP_TBL (USER_ID, ROLE_ID, CREATED_BY, CREATED_IP)
VALUES (10000002, 11000002, 'DUSHMANTA', '100.125.49.24');  
COMMIT;

INSERT INTO AIRLINE_MENU_MSTR_TBL (MENU_ID, MENU_NAME, CREATED_BY, CREATED_IP)
VALUES (AIRLINE_MENU_MSTR_SEQ.NEXTVAL, 'CREATE USER', 'DARSHIL', '100.125.49.24');

INSERT INTO AIRLINE_MENU_MSTR_TBL (MENU_ID, MENU_NAME, CREATED_BY, CREATED_IP)
VALUES (AIRLINE_MENU_MSTR_SEQ.NEXTVAL, 'ASSIGN ROLE TO USER', 'DUSHMANTA', '100.125.49.24');
COMMIT;

INSERT INTO AIRLINE_ROLE_MENU_MAP_TBL (ROLE_ID, MENU_ID, CREATED_BY, CREATED_IP)
VALUES (11000001, 12000001, 'DUSHMANTA', '100.125.49.24');  

INSERT INTO AIRLINE_ROLE_MENU_MAP_TBL (ROLE_ID, MENU_ID, CREATED_BY, CREATED_IP)
VALUES (11000001, 12000002, 'DUSHMANTA', '100.125.49.24');  
COMMIT;

-- =============================================================================
-- 4. STORED PROCEDURES
-- =============================================================================

CREATE OR REPLACE PROCEDURE AIRLINE_AIRPORT_CREATE_USP (
    P_AIRPORTNAME IN VARCHAR2,
    P_AIRPORTCODE IN VARCHAR2,
    P_CITY_ID     IN VARCHAR2,
    P_ACTION      IN VARCHAR2,
    P_CURSOR      OUT SYS_REFCURSOR,
    P_DATA        OUT VARCHAR2
)
IS
    V_COUNT NUMBER;
BEGIN
    IF P_ACTION = 'DROPDOWN' THEN
        OPEN P_CURSOR FOR
            SELECT CITY_ID, CITY_NAME
            FROM AIRLINE_CITY_MSTR_TBL
            WHERE IS_ACTIVE = 'Y'
            ORDER BY CITY_NAME;

        P_DATA := 'CITY LIST FETCHED SUCCESSFULLY';

    ELSIF P_ACTION = 'SELECT' THEN
        OPEN P_CURSOR FOR
            SELECT A.AIRPORT_ID, A.AIRPORT_NAME, A.AIRPORT_CODE, A.CITY_ID, C.CITY_NAME, C.COUNTRY_NAME
            FROM AIRLINE_AIRPORT_MSTR_TBL A
            LEFT JOIN AIRLINE_CITY_MSTR_TBL C ON A.CITY_ID = C.CITY_ID
            WHERE A.IS_ACTIVE = 'Y' OR A.IS_ACTIVE IS NULL
            ORDER BY A.AIRPORT_NAME;

        P_DATA := 'AIRPORT LIST FETCHED SUCCESSFULLY';

    ELSIF P_ACTION = 'INSERT' THEN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM AIRLINE_AIRPORT_MSTR_TBL
        WHERE UPPER(AIRPORT_NAME) = UPPER(P_AIRPORTNAME)
          AND UPPER(AIRPORT_CODE) = UPPER(P_AIRPORTCODE);

        IF V_COUNT > 0 THEN
            P_DATA := 'THE AIRPORT IS ALREADY THERE';
        ELSE
            INSERT INTO AIRLINE_AIRPORT_MSTR_TBL
                (AIRPORT_ID, AIRPORT_NAME, AIRPORT_CODE, CITY_ID, CREATED_BY, CREATED_IP)
            VALUES
                (AIRLINE_AIRPORT_MSTR_SEQ.NEXTVAL,
                 UPPER(P_AIRPORTNAME),
                 UPPER(P_AIRPORTCODE),
                 TO_NUMBER(P_CITY_ID),
                 'DUSHMANTA',
                 '100.125.49.24');

            P_DATA := 'AIRPORT INSERTED SUCCESSFULLY';
            COMMIT;
        END IF;

    ELSE
        P_DATA := 'INVALID ACTION';
    END IF;
END AIRLINE_AIRPORT_CREATE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ASSIGN_OR_UPDATE_ROLE_TO_USER_USP (
    P_USER_ID      IN NUMBER,
    P_ROLE_ID      IN NUMBER,
    P_CREATED_BY   IN VARCHAR2,
    P_CREATED_IP   IN VARCHAR2,
    P_DATA         OUT VARCHAR2
)
IS
    V_ROLE_COUNT NUMBER;
    V_USER_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_ROLE_COUNT
    FROM AIRLINE_ROLE_MSTR_TBL
    WHERE ROLE_ID = P_ROLE_ID
      AND IS_ACTIVE = 'Y';

    IF V_ROLE_COUNT = 0 THEN
        P_DATA := 'ROLE IS NOT ACTIVE';
        RETURN;
    END IF;

    SELECT COUNT(*)
    INTO V_USER_COUNT
    FROM AIRLINE_USER_ROLE_MAP_TBL
    WHERE USER_ID = P_USER_ID;

    IF V_USER_COUNT > 0 THEN
        UPDATE AIRLINE_USER_ROLE_MAP_TBL
        SET ROLE_ID      = P_ROLE_ID,
            UPDATED_TIME = SYSTIMESTAMP,
            UPDATED_BY   = P_CREATED_BY,
            UPDATED_IP   = P_CREATED_IP
        WHERE USER_ID = P_USER_ID;
        P_DATA := 'ROLE UPDATED SUCCESSFULLY';
    ELSE
        INSERT INTO AIRLINE_USER_ROLE_MAP_TBL
            (USER_ID, ROLE_ID, IS_ACTIVE, CREATED_BY, CREATED_IP)
        VALUES
            (P_USER_ID, P_ROLE_ID, 'Y', P_CREATED_BY, P_CREATED_IP);
        P_DATA := 'ROLE ASSIGNED SUCCESSFULLY';
    END IF;
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_DATA := SQLERRM;
END AIRLINE_ASSIGN_OR_UPDATE_ROLE_TO_USER_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ASSIGN_ROLE_SCREEN_USP (
    P_USERS OUT SYS_REFCURSOR,
    P_ROLES OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN P_USERS FOR
        SELECT USER_ID, USERNAME, MOBILENO
        FROM AIRLINE_USER_MSTR_TBL
        WHERE IS_ACTIVE = 'Y'
        ORDER BY USERNAME;

    OPEN P_ROLES FOR
        SELECT ROLE_ID, ROLE_NAME
        FROM AIRLINE_ROLE_MSTR_TBL
        WHERE IS_ACTIVE = 'Y'
        ORDER BY ROLE_NAME;
END AIRLINE_ASSIGN_ROLE_SCREEN_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_CHECK_MOBILE_USP (
    P_MOBILENO IN NUMBER,
    P_COUNT    OUT NUMBER
)
IS
BEGIN
    SELECT COUNT(*) INTO P_COUNT
    FROM AIRLINE_USER_MSTR_TBL
    WHERE MOBILENO = P_MOBILENO;
END AIRLINE_CHECK_MOBILE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_CITY_CREATE_USP (
    P_CITYNAME    IN VARCHAR2,
    P_STATENAME   IN VARCHAR2,
    P_COUNTRYNAME IN VARCHAR2,
    P_ACTION      IN VARCHAR2,
    P_CURSOR      OUT SYS_REFCURSOR,
    P_DATA        OUT VARCHAR2
)
IS
    V_COUNT NUMBER;
BEGIN
    IF P_ACTION = 'INSERT' THEN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM AIRLINE_CITY_MSTR_TBL
        WHERE CITY_NAME = UPPER(P_CITYNAME)
          AND STATE_NAME = UPPER(P_STATENAME)
          AND COUNTRY_NAME = UPPER(P_COUNTRYNAME);

        IF V_COUNT > 0 THEN
            P_DATA := 'THE CITY IS ALREADY THERE';
        ELSE
            INSERT INTO AIRLINE_CITY_MSTR_TBL
                (CITY_ID, CITY_NAME, STATE_NAME, COUNTRY_NAME, CREATED_BY, CREATED_IP)
            VALUES
                (AIRLINE_CITY_MSTR_SEQ.NEXTVAL, UPPER(P_CITYNAME), UPPER(P_STATENAME), UPPER(P_COUNTRYNAME), 'DUSHMANTA', '100.125.49.24');

            P_DATA := 'CITY INSERTED SUCCESSFULLY';
            COMMIT;
        END IF;

        OPEN P_CURSOR FOR
            SELECT CITY_NAME, STATE_NAME, COUNTRY_NAME
            FROM AIRLINE_CITY_MSTR_TBL
            ORDER BY CITY_NAME;

    ELSIF P_ACTION = 'SELECT' THEN
        OPEN P_CURSOR FOR
            SELECT CITY_NAME, STATE_NAME, COUNTRY_NAME
            FROM AIRLINE_CITY_MSTR_TBL
            ORDER BY CITY_NAME;
        P_DATA := 'SELECT SUCCESSFUL';

    ELSE
        P_DATA := 'INVALID ACTION';
    END IF;   
END AIRLINE_CITY_CREATE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_FIND_ROLE_USER_USP (
    P_USER_ID IN NUMBER,
    P_RECORD OUT SYS_REFCURSOR
) IS
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_FIND_ROLE_USER_USP P_USER_ID=' || P_USER_ID);
    COMMIT; 

    OPEN P_RECORD FOR
        SELECT R.ROLE_ID, R.ROLE_NAME 
        FROM AIRLINE_ROLE_MSTR_TBL R
        JOIN AIRLINE_USER_ROLE_MAP_TBL MAP ON R.ROLE_ID = MAP.ROLE_ID
        WHERE MAP.USER_ID = P_USER_ID;
END AIRLINE_FIND_ROLE_USER_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_FLIGHT_COMPANY_CREATE_USP (
    P_COMPANYNAME IN VARCHAR2,
    P_COMPANYCODE IN VARCHAR2,
    P_ACTION      IN VARCHAR2,
    P_CURSOR      OUT SYS_REFCURSOR,
    P_DATA        OUT VARCHAR2
)
IS
    V_COUNT NUMBER;
BEGIN
    IF UPPER(P_ACTION) = 'INSERT' THEN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM AIRLINE_FLIGHT_COMPANY_MSTR_TBL
        WHERE COMPANY_NAME = UPPER(P_COMPANYNAME)
          AND COMPANY_CODE = UPPER(P_COMPANYCODE);

        IF V_COUNT > 0 THEN
            P_DATA := 'THE FLIGHT COMPANY ALREADY EXISTS';
        ELSE
            INSERT INTO AIRLINE_FLIGHT_COMPANY_MSTR_TBL
                (COMPANY_ID, COMPANY_NAME, COMPANY_CODE, CREATED_BY, CREATED_IP)
            VALUES
                (AIRLINE_FLIGHT_COMPANY_MSTR_SEQ.NEXTVAL, UPPER(P_COMPANYNAME), UPPER(P_COMPANYCODE), 'DUSHMANTA', '100.125.49.24');

            P_DATA := 'FLIGHT COMPANY CREATED SUCCESSFULLY';
        END IF;

    ELSIF UPPER(P_ACTION) = 'DROPDOWN' THEN
        OPEN P_CURSOR FOR
            SELECT COMPANY_ID, COMPANY_NAME, COMPANY_CODE
            FROM AIRLINE_FLIGHT_COMPANY_MSTR_TBL
            WHERE IS_ACTIVE = 'Y'
            ORDER BY COMPANY_NAME;

        P_DATA := 'FLIGHT COMPANY DATA FETCHED SUCCESSFULLY';

    ELSE
        P_DATA := 'INVALID ACTION';
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        P_DATA := SQLERRM;
END AIRLINE_FLIGHT_COMPANY_CREATE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_ACTIVE_CREW_COUNT_USP (
    p_active_cnt OUT NUMBER
) IS
BEGIN
    SELECT COUNT(*) INTO p_active_cnt FROM AIRLINE_USER_MSTR_TBL WHERE IS_ACTIVE = 'Y';
END AIRLINE_GET_ACTIVE_CREW_COUNT_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_ALL_USERS_USP (
    P_RESULT OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULT FOR
        SELECT  u.USER_ID,
                u.USERNAME,
                u.MOBILENO,
                u.PASSPORT_IMG,
                u.IS_ACTIVE,
                r.ROLE_NAME
        FROM    AIRLINE_USER_MSTR_TBL u
        LEFT JOIN AIRLINE_USER_ROLE_MAP_TBL urm
               ON u.USER_ID = urm.USER_ID
              AND urm.IS_ACTIVE = 'Y'
        LEFT JOIN AIRLINE_ROLE_MSTR_TBL r
               ON urm.ROLE_ID = r.ROLE_ID
              AND r.IS_ACTIVE = 'Y'
        ORDER BY u.USER_ID;
EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END AIRLINE_GET_ALL_USERS_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_MENU_DROP_DOWN_MAPPED_USP (
    P_ROLE_ID IN VARCHAR2,
    P_RECORD  OUT SYS_REFCURSOR
)
IS
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_GET_MENU_DROP_DOWN_MAPPED_USP P_ROLE_ID = ' || NVL(P_ROLE_ID, 'NULL'));
    COMMIT;

    OPEN P_RECORD FOR
        SELECT DISTINCT MM.MENU_ID, MM.MENU_NAME  
        FROM AIRLINE_MENU_MSTR_TBL MM 
        WHERE MM.IS_ACTIVE = 'Y'
          AND MM.MENU_ID IN (
              SELECT MM_MAP.MENU_ID
              FROM AIRLINE_ROLE_MENU_MAP_TBL MM_MAP 
              JOIN AIRLINE_MENU_MSTR_TBL MENU ON MENU.MENU_ID = MM_MAP.MENU_ID
              WHERE MM_MAP.ROLE_ID = P_ROLE_ID
          );
END AIRLINE_GET_MENU_DROP_DOWN_MAPPED_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_MENU_DROP_DOWN_NOTMAPPED_USP (
    P_ROLE_ID IN VARCHAR2,
    P_RECORD  OUT SYS_REFCURSOR
)
IS
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_GET_MENU_DROP_DOWN_NOTMAPPED_USP P_ROLE_ID = ' || NVL(P_ROLE_ID, 'NULL'));
    COMMIT;

    OPEN P_RECORD FOR
        SELECT DISTINCT MM.MENU_ID, MM.MENU_NAME  
        FROM AIRLINE_MENU_MSTR_TBL MM 
        WHERE MM.IS_ACTIVE = 'Y'
          AND MM.MENU_ID NOT IN (
              SELECT MM_MAP.MENU_ID
              FROM AIRLINE_ROLE_MENU_MAP_TBL MM_MAP 
              JOIN AIRLINE_MENU_MSTR_TBL MENU ON MENU.MENU_ID = MM_MAP.MENU_ID
              WHERE MM_MAP.ROLE_ID = P_ROLE_ID
          );
END AIRLINE_GET_MENU_DROP_DOWN_NOTMAPPED_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_MENU_USP (
    P_USERNAME IN VARCHAR2,
    P_RECORD   OUT SYS_REFCURSOR
)
IS
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_GET_MENU_USP P_USERNAME = ' || P_USERNAME);
    COMMIT;

    OPEN P_RECORD FOR
        SELECT MM.MENU_NAME 
        FROM AIRLINE_USER_MSTR_TBL U
        JOIN AIRLINE_USER_ROLE_MAP_TBL UR ON U.USER_ID = UR.USER_ID 
        JOIN AIRLINE_ROLE_MENU_MAP_TBL RM ON UR.ROLE_ID = RM.ROLE_ID
        JOIN AIRLINE_MENU_MSTR_TBL MM ON RM.MENU_ID = MM.MENU_ID
        WHERE LOWER(U.USERNAME) = LOWER(P_USERNAME); 
END AIRLINE_GET_MENU_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_PASSPORT_IMG_USP (
    P_USER_ID       IN NUMBER,
    P_PASSPORT_IMG  OUT VARCHAR2
)
IS
BEGIN
    SELECT PASSPORT_IMG INTO P_PASSPORT_IMG
    FROM AIRLINE_USER_MSTR_TBL
    WHERE USER_ID = P_USER_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_PASSPORT_IMG := NULL;
END AIRLINE_GET_PASSPORT_IMG_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_ROLE_USP (
    P_USERNAME IN VARCHAR2,
    P_RECORD OUT SYS_REFCURSOR
) IS
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_GET_ROLE_USP P_USERNAME=' || NVL(P_USERNAME, 'NULL'));
    COMMIT;

    OPEN P_RECORD FOR
        SELECT ROLE_ID, ROLE_NAME
        FROM AIRLINE_ROLE_MSTR_TBL
        ORDER BY ROLE_NAME;
END AIRLINE_GET_ROLE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_USER_PROFILE_FULL_USP (
    P_USER_IDENTIFIER IN VARCHAR2,
    P_LOGIN_MODE      IN VARCHAR2,
    P_RESULT          OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULT FOR
        SELECT  u.USER_ID,
                u.USERNAME,
                u.MOBILENO,
                u.PASSPORT_IMG,
                u.IS_ACTIVE,
                r.ROLE_NAME
        FROM    AIRLINE_USER_MSTR_TBL u
        LEFT JOIN AIRLINE_USER_ROLE_MAP_TBL urm
               ON u.USER_ID = urm.USER_ID
              AND urm.IS_ACTIVE = 'Y'
        LEFT JOIN AIRLINE_ROLE_MSTR_TBL r
               ON urm.ROLE_ID = r.ROLE_ID
              AND r.IS_ACTIVE = 'Y'
        WHERE   ( P_LOGIN_MODE = 'U' AND LOWER(u.USERNAME) = LOWER(P_USER_IDENTIFIER) )
           OR   ( P_LOGIN_MODE <> 'U' AND u.MOBILENO = TO_NUMBER(P_USER_IDENTIFIER) )
        ORDER BY u.USER_ID;
EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END AIRLINE_GET_USER_PROFILE_FULL_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_USER_PROFILE_USP (
    P_USER_IDENTIFIER IN VARCHAR2,
    P_LOGIN_MODE      IN VARCHAR2,
    P_USER_ID         OUT NUMBER,
    P_USERNAME        OUT VARCHAR2,
    P_PASSPORT_IMG    OUT VARCHAR2,
    P_ROLE_NAME       OUT VARCHAR2
)
IS
BEGIN
    IF P_LOGIN_MODE = 'U' THEN
        SELECT USER_ID, USERNAME, PASSPORT_IMG
        INTO P_USER_ID, P_USERNAME, P_PASSPORT_IMG
        FROM AIRLINE_USER_MSTR_TBL
        WHERE LOWER(USERNAME) = LOWER(P_USER_IDENTIFIER);
    ELSE
        SELECT USER_ID, USERNAME, PASSPORT_IMG
        INTO P_USER_ID, P_USERNAME, P_PASSPORT_IMG
        FROM AIRLINE_USER_MSTR_TBL
        WHERE MOBILENO = TO_NUMBER(P_USER_IDENTIFIER);
    END IF;

    BEGIN
        SELECT r.ROLE_NAME
        INTO P_ROLE_NAME
        FROM AIRLINE_USER_ROLE_MAP_TBL urm
        JOIN AIRLINE_ROLE_MSTR_TBL r ON urm.ROLE_ID = r.ROLE_ID
        WHERE urm.USER_ID = P_USER_ID
          AND urm.IS_ACTIVE = 'Y'
          AND r.IS_ACTIVE = 'Y';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_ROLE_NAME := NULL;
    END;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_USER_ID := NULL;
        P_USERNAME := NULL;
        P_PASSPORT_IMG := NULL;
        P_ROLE_NAME := NULL;
END AIRLINE_GET_USER_PROFILE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_USER_ROLE_USP (
    P_USER_ID IN NUMBER,
    P_RECORD OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN P_RECORD FOR
        SELECT U.USER_ID, U.USERNAME, R.ROLE_ID, R.ROLE_NAME
        FROM AIRLINE_USER_MSTR_TBL U
        JOIN AIRLINE_USER_ROLE_MAP_TBL UR ON U.USER_ID = UR.USER_ID
        JOIN AIRLINE_ROLE_MSTR_TBL R ON UR.ROLE_ID = R.ROLE_ID
        WHERE U.USER_ID = P_USER_ID
          AND UR.IS_ACTIVE = 'Y';
END AIRLINE_GET_USER_ROLE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_USER_USP (
    P_USERNAME IN VARCHAR2,
    P_RECORD   OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN P_RECORD FOR
        SELECT USER_ID, USERNAME FROM AIRLINE_USER_MSTR_TBL;
END AIRLINE_GET_USER_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_MENU_MSTR_INSERT_USP (
    P_MENU_NAME IN VARCHAR2,
    P_DATA      OUT VARCHAR2
)
IS
    V_ERROR VARCHAR2(4000);
    V_COUNT NUMBER;
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_MENU_MSTR_INSERT_USP P_MENU_NAME = ' || P_MENU_NAME);
    COMMIT;

    SELECT COUNT(*)
    INTO V_COUNT
    FROM AIRLINE_MENU_MSTR_TBL
    WHERE MENU_NAME = P_MENU_NAME;

    IF V_COUNT > 0 THEN
        P_DATA := 'MENU ALREADY EXISTS';
    ELSE
        INSERT INTO AIRLINE_MENU_MSTR_TBL (MENU_ID, MENU_NAME)
        VALUES (AIRLINE_MENU_MSTR_SEQ.NEXTVAL, P_MENU_NAME);
        P_DATA := 'MENU CREATED SUCCESSFULLY';
    END IF;
EXCEPTION
    WHEN OTHERS THEN 
        V_ERROR := SQLERRM || ', ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || ', SPNAME AIRLINE_MENU_MSTR_INSERT_USP P_MENU_NAME ' || P_MENU_NAME;
        ROLLBACK;
        INSERT INTO AIRLINE_ERROR_LOG_TBL(ERROR_DESC) VALUES (V_ERROR);
        COMMIT;
END AIRLINE_MENU_MSTR_INSERT_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_MENU_OPERATION_USP (
    P_MENU_ID      IN VARCHAR2,
    P_MENUNAME     IN VARCHAR2,
    P_ACTION       IN VARCHAR2,
    P_DATA_CREATE  OUT VARCHAR2,
    P_DATA_DELETE  OUT VARCHAR2,
    P_CURSOR       OUT SYS_REFCURSOR
)
IS
    V_COUNT1 NUMBER := 0;
    V_COUNT2 NUMBER := 0;
BEGIN
    IF UPPER(P_ACTION) = 'CREATE' THEN
        SELECT COUNT(*) INTO V_COUNT1 FROM AIRLINE_MENU_MSTR_TBL
        WHERE UPPER(MENU_NAME) = UPPER(TRIM(P_MENUNAME));
        IF V_COUNT1 > 0 THEN
            P_DATA_CREATE := 'THE MENU ALREADY EXISTS';
        ELSE
            INSERT INTO AIRLINE_MENU_MSTR_TBL (MENU_ID, MENU_NAME)
            VALUES (AIRLINE_MENU_MSTR_SEQ.NEXTVAL, P_MENUNAME);
            P_DATA_CREATE := 'MENU CREATED SUCCESSFULLY';
        END IF;

    ELSIF UPPER(P_ACTION) = 'DROPDOWN' THEN
        OPEN P_CURSOR FOR
            SELECT MENU_ID, MENU_NAME
            FROM AIRLINE_MENU_MSTR_TBL
            ORDER BY MENU_NAME;

    ELSIF UPPER(P_ACTION) = 'DELETE' THEN
        SELECT COUNT(*) INTO V_COUNT2 FROM AIRLINE_MENU_MSTR_TBL
        WHERE MENU_ID = P_MENU_ID;
        IF V_COUNT2 = 0 THEN
            P_DATA_DELETE := 'THE MENU DOES NOT EXIST';
        ELSE
            DELETE FROM AIRLINE_MENU_MSTR_TBL
            WHERE MENU_ID = P_MENU_ID;
            P_DATA_DELETE := 'MENU DELETED SUCCESSFULLY';
        END IF;
    END IF;
END AIRLINE_MENU_OPERATION_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ROLE_MENU_MAP_DELETE_USP (
    P_ROLE_ID IN NUMBER,
    P_MENU_ID IN NUMBER,
    P_DATA    OUT VARCHAR2
) AS
BEGIN
    DELETE FROM AIRLINE_ROLE_MENU_MAP_TBL 
    WHERE ROLE_ID = P_ROLE_ID AND MENU_ID = P_MENU_ID;
    COMMIT;
    P_DATA := 'SUCCESS';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_DATA := SQLERRM;
END AIRLINE_ROLE_MENU_MAP_DELETE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ROLE_MENU_MAP_INSERT_USP (
    P_ROLE_ID IN NUMBER,
    P_MENU_ID IN NUMBER,
    P_DATA    OUT VARCHAR2
) AS
BEGIN
    INSERT INTO AIRLINE_ROLE_MENU_MAP_TBL (
        ROLE_ID, MENU_ID, IS_ACTIVE, CREATED_TIME, CREATED_BY
    ) VALUES (
        P_ROLE_ID, P_MENU_ID, 'Y', SYSTIMESTAMP, 'ADMIN'
    );
    COMMIT;
    P_DATA := 'SUCCESS';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_DATA := SQLERRM;
END AIRLINE_ROLE_MENU_MAP_INSERT_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ROLE_MSTR_INSERT_USP (
    P_ROLE_NAME IN VARCHAR2,
    P_DATA      OUT VARCHAR2
)
IS
    V_ERROR VARCHAR2(4000);
    V_COUNT NUMBER;
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_ROLE_MSTR_INSERT_USP P_ROLE_NAME = ' || P_ROLE_NAME);
    COMMIT;

    SELECT COUNT(*)
    INTO V_COUNT
    FROM AIRLINE_ROLE_MSTR_TBL
    WHERE ROLE_NAME = P_ROLE_NAME;

    IF V_COUNT > 0 THEN
        P_DATA := 'ROLE ALREADY EXISTS';
    ELSE
        INSERT INTO AIRLINE_ROLE_MSTR_TBL (ROLE_ID, ROLE_NAME)
        VALUES (AIRLINE_ROLE_MSTR_SEQ.NEXTVAL, P_ROLE_NAME);
        P_DATA := 'ROLE CREATED SUCCESSFULLY';
    END IF;
EXCEPTION
    WHEN OTHERS THEN 
        V_ERROR := SQLERRM || ', ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || ', SPNAME AIRLINE_ROLE_MSTR_INSERT_USP P_ROLE_NAME ' || P_ROLE_NAME;
        ROLLBACK;
        INSERT INTO AIRLINE_ERROR_LOG_TBL(ERROR_DESC) VALUES (V_ERROR);
        COMMIT;
END AIRLINE_ROLE_MSTR_INSERT_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ROLE_OPERATION_USP (
    P_ROLE_ID      IN VARCHAR2,
    P_ROLENAME     IN VARCHAR2,
    P_ACTION       IN VARCHAR2,
    P_DATA_CREATE  OUT VARCHAR2,
    P_DATA_DELETE  OUT VARCHAR2,
    P_CURSOR       OUT SYS_REFCURSOR
)
IS
    V_COUNT1 NUMBER := 0;
    V_COUNT2 NUMBER := 0;
BEGIN
    IF UPPER(P_ACTION) = 'CREATE' THEN
        SELECT COUNT(*) INTO V_COUNT1 FROM AIRLINE_ROLE_MSTR_TBL
        WHERE UPPER(ROLE_NAME) = UPPER(TRIM(P_ROLENAME));
        IF V_COUNT1 > 0 THEN
            P_DATA_CREATE := 'THE ROLE ALREADY EXISTS';
        ELSE
            INSERT INTO AIRLINE_ROLE_MSTR_TBL (ROLE_ID, ROLE_NAME)
            VALUES (AIRLINE_ROLE_MSTR_SEQ.NEXTVAL, P_ROLENAME);
            P_DATA_CREATE := 'ROLE CREATED SUCCESSFULLY';
        END IF;

    ELSIF UPPER(P_ACTION) = 'DROPDOWN' THEN
        OPEN P_CURSOR FOR
            SELECT ROLE_ID, ROLE_NAME
            FROM AIRLINE_ROLE_MSTR_TBL
            ORDER BY ROLE_NAME;

    ELSIF UPPER(P_ACTION) = 'DELETE' THEN
        SELECT COUNT(*) INTO V_COUNT2 FROM AIRLINE_ROLE_MSTR_TBL
        WHERE ROLE_ID = P_ROLE_ID;
        IF V_COUNT2 = 0 THEN
            P_DATA_DELETE := 'THE ROLE DOES NOT EXIST TO DELETE';
        ELSE
            DELETE FROM AIRLINE_ROLE_MSTR_TBL
            WHERE ROLE_ID = P_ROLE_ID;
            P_DATA_DELETE := 'ROLE DELETED SUCCESSFULLY';
        END IF;
    END IF;
END AIRLINE_ROLE_OPERATION_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_UPDATE_OTP_USP (
    P_MOBILENO IN NUMBER,
    P_OTP      IN NUMBER
)
IS
BEGIN
    UPDATE AIRLINE_USER_MSTR_TBL
    SET OTP = P_OTP
    WHERE MOBILENO = P_MOBILENO;
    COMMIT;
END AIRLINE_UPDATE_OTP_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_USER_CREATE_USP (
    P_USERNAME      IN  VARCHAR2,
    P_MOBILENO      IN  NUMBER,
    P_PASSWD        IN  VARCHAR2,
    P_MPIN          IN  NUMBER, 
    P_PASSPORT_IMG  IN  VARCHAR2,
    P_ACTIVE_CREW   IN  NUMBER,
    P_DATA          OUT VARCHAR2
)
IS
    V_ERROR VARCHAR2(4000);
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO   V_COUNT
    FROM   AIRLINE_USER_MSTR_TBL
    WHERE  USERNAME = P_USERNAME
       OR  MOBILENO = P_MOBILENO;

    IF V_COUNT > 0 THEN
        P_DATA := 'USER ALREADY EXISTS';
    ELSE
        INSERT INTO AIRLINE_USER_MSTR_TBL 
            (USER_ID, USERNAME, MOBILENO, PASSWD, MPIN, PASSPORT_IMG, IS_ACTIVE)
        VALUES 
            (AIRLINE_USER_MSTR_SEQ.NEXTVAL, P_USERNAME, P_MOBILENO, P_PASSWD, P_MPIN, P_PASSPORT_IMG, 'Y');

        P_DATA := 'USER CREATED SUCCESSFULLY';
    END IF;

EXCEPTION
    WHEN OTHERS THEN 
        V_ERROR := SQLERRM || ', ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || ', SPNAME AIRLINE_USER_CREATE_USP P_USERNAME ' || P_USERNAME || ' P_MOBILENO ' || P_MOBILENO;
        P_DATA := 'ERROR: ' || SQLERRM;
        ROLLBACK;

        BEGIN
            INSERT INTO AIRLINE_ERROR_LOG_TBL(ERROR_DESC) VALUES (V_ERROR);
            COMMIT;
        EXCEPTION
            WHEN OTHERS THEN
                NULL;
        END;
END AIRLINE_USER_CREATE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_USER_LOGIN_USP (
    P_LOGIN_MODE IN VARCHAR2,
    P_USERNAME   IN VARCHAR2,
    P_PASSWD     IN VARCHAR2,
    P_MOBILENO   IN NUMBER,
    P_OTP        IN NUMBER,
    P_DATA       OUT VARCHAR2
)
IS
    V_COUNT NUMBER;
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_USER_LOGIN_USP P_LOGIN_MODE = ' || P_LOGIN_MODE  
            || ' P_USERNAME = ' || P_USERNAME 
            || ' P_PASSWD = ' || P_PASSWD 
            || ' P_MOBILENO = ' || P_MOBILENO 
            || ' P_OTP = ' || P_OTP);
    COMMIT;

    IF P_LOGIN_MODE = 'U' THEN
        SELECT COUNT(*) INTO V_COUNT FROM AIRLINE_USER_MSTR_TBL 
        WHERE UPPER(USERNAME) = UPPER(P_USERNAME) AND UPPER(PASSWD) = UPPER(P_PASSWD);

        IF V_COUNT = 1 THEN
            P_DATA := 'Y';
        ELSE                  
            P_DATA := 'N';
        END IF;
    END IF;

    IF P_LOGIN_MODE = 'M' THEN
        SELECT COUNT(*) INTO V_COUNT FROM AIRLINE_USER_MSTR_TBL 
        WHERE LOWER(MOBILENO) = P_MOBILENO AND UPPER(OTP) = P_OTP;

        IF V_COUNT = 1 THEN
            P_DATA := 'Y';
        ELSE                  
            P_DATA := 'N';
        END IF;
    END IF;
END AIRLINE_USER_LOGIN_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_USER_ROLE_MAP_INSERT_USP ( 
    P_USER_ID IN NUMBER,       
    P_ROLE_ID IN NUMBER,        
    P_DATA    OUT VARCHAR2       
) AS
    V_COUNT NUMBER;
    V_ERROR VARCHAR2(4000);
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_USER_ROLE_MAP_INSERT_USP P_USER_ID ' || P_USER_ID || ' P_ROLE_ID ' || P_ROLE_ID);
    COMMIT;

    INSERT INTO AIRLINE_USER_ROLE_MAP_TBL (USER_ID, ROLE_ID)
    VALUES (P_USER_ID, P_ROLE_ID);
EXCEPTION
    WHEN OTHERS THEN 
        V_ERROR := SQLERRM || ', ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || ', SPNAME AIRLINE_USER_ROLE_MAP_INSERT_USP P_USER_ID ' || P_USER_ID || ' P_ROLE_ID ' || P_ROLE_ID;
        ROLLBACK;
        INSERT INTO AIRLINE_ERROR_LOG_TBL(ERROR_DESC) VALUES (V_ERROR);
        COMMIT;
END AIRLINE_USER_ROLE_MAP_INSERT_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_USER_ROLE_MAP_UPDATE_USP ( 
    P_USER_ID IN NUMBER,       
    P_ROLE_ID IN NUMBER,        
    P_DATA    OUT VARCHAR2       
) AS
    V_COUNT NUMBER;
    V_ERROR VARCHAR2(4000);
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_USER_ROLE_MAP_UPDATE_USP P_USER_ID ' || P_USER_ID || ' P_ROLE_ID ' || P_ROLE_ID);
    COMMIT;

    UPDATE AIRLINE_USER_ROLE_MAP_TBL
    SET ROLE_ID = P_ROLE_ID
    WHERE USER_ID = P_USER_ID;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN 
        V_ERROR := SQLERRM || ', ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || ', SPNAME AIRLINE_USER_ROLE_MAP_UPDATE_USP P_USER_ID ' || P_USER_ID || ' P_ROLE_ID ' || P_ROLE_ID;
        ROLLBACK;
        INSERT INTO AIRLINE_ERROR_LOG_TBL(ERROR_DESC) VALUES (V_ERROR);
        COMMIT;
END AIRLINE_USER_ROLE_MAP_UPDATE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_CUSTOMER_REGD_USP (
    P_PASSENGERNAME IN VARCHAR2,
    P_GENDER        IN VARCHAR2,
    P_DOB           IN DATE,
    P_MOBILENO      IN NUMBER,
    P_EMAILID       IN VARCHAR2,
    P_PASSPORTNO    IN VARCHAR2,
    P_DATA          OUT VARCHAR2
)
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL
    WHERE UPPER(EMAIL_ID) = UPPER(P_EMAILID)
      AND MOBILE_NO = P_MOBILENO
      AND UPPER(PASSPORT_NO) = UPPER(P_PASSPORTNO);

    IF V_COUNT > 0 THEN
        P_DATA := 'THE CUSTOMER IS ALREADY REGISTERED';
    ELSE
        INSERT INTO AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL (
            PASSENGER_ID, PASSENGER_NAME, GENDER, DOB, MOBILE_NO, EMAIL_ID, PASSPORT_NO, CREATED_BY, CREATED_IP
        ) VALUES (
            AIRLINE_PASSENGERS_REGD_FORM_MSTR_SEQ.NEXTVAL, UPPER(P_PASSENGERNAME), UPPER(P_GENDER), P_DOB, P_MOBILENO, 
            UPPER(P_EMAILID), UPPER(P_PASSPORTNO), 'DUSHMANTA', '100.125.49.24'
        );
        COMMIT;

        P_DATA := 'CUSTOMER REGISTERED SUCCESSFULLY';
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_DATA := SQLERRM;
END AIRLINE_CUSTOMER_REGD_USP;
/
