-- =============================================================================
-- AIRLINE OPERATION SUITE (AOS) DATABASE SCHEMA AND PL/SQL STORED PROCEDURES
-- Database Target: Oracle Database 12c / 19c / 21c / 23c
-- =============================================================================

-- =============================================================================
-- 1. TABLE CREATION
-- =============================================================================

CREATE TABLE AIRLINE_USER_MSTR_TBL (
	USER_ID       NUMBER(10),
	USERNAME      VARCHAR2(50) NOT NULL,
	MOBILENO      NUMBER(10) CONSTRAINT MOBILENO_CHK CHECK(LENGTH(MOBILENO)=10),
	PASSWD        VARCHAR2(100) NOT NULL,
	MPIN          NUMBER(4),
	OTP           NUMBER(6),
	PASSPORT_IMG  VARCHAR2(2000),
	IS_ACTIVE     CHAR(1) DEFAULT 'Y',
	CREATED_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP,
	CREATED_BY    VARCHAR2(10),
	UPDATED_TIME  TIMESTAMP,
	UPDATED_BY    VARCHAR2(10),
	CREATED_IP    VARCHAR2(100),
	UPDATED_IP    VARCHAR2(100),      
	CONSTRAINT PK_USER_ID PRIMARY KEY (USER_ID),
	CONSTRAINT UK_MOBILENO UNIQUE (MOBILENO),
	CONSTRAINT UK_USERNAME UNIQUE (USERNAME)      
);
/

CREATE TABLE AIRLINE_ROLE_MSTR_TBL (
	ROLE_ID       NUMBER(10),
	ROLE_NAME     VARCHAR2(100) NOT NULL,
	IS_ACTIVE     CHAR(1) DEFAULT 'Y',
	CREATED_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP,
	CREATED_BY    VARCHAR2(10),
	UPDATED_TIME  TIMESTAMP,
	UPDATED_BY    VARCHAR2(10),
	CREATED_IP    VARCHAR2(100),
	UPDATED_IP    VARCHAR2(100),
	CONSTRAINT PK_ROLE_ID PRIMARY KEY (ROLE_ID)
);
/

CREATE TABLE AIRLINE_USER_ROLE_MAP_TBL (
	ROW_NO        NUMBER(35) GENERATED ALWAYS AS IDENTITY,
	USER_ID       NUMBER(10),
	ROLE_ID       NUMBER(10),
	IS_ACTIVE     CHAR(1) DEFAULT 'Y',
	CREATED_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP,
	CREATED_BY    VARCHAR2(10),
	UPDATED_TIME  TIMESTAMP,
	UPDATED_BY    VARCHAR2(10),
	CREATED_IP    VARCHAR2(100),
	UPDATED_IP    VARCHAR2(100),
	CONSTRAINT PK_ROW_NO PRIMARY KEY (ROW_NO),
	CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE_ID),
	CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES AIRLINE_USER_MSTR_TBL(USER_ID),
	CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES AIRLINE_ROLE_MSTR_TBL(ROLE_ID)
);
/

CREATE TABLE AIRLINE_MENU_MSTR_TBL (
	MENU_ID       NUMBER(10),
	MENU_NAME     VARCHAR2(100) NOT NULL,
	IS_ACTIVE     CHAR(1) DEFAULT 'Y',
	CREATED_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP,
	CREATED_BY    VARCHAR2(50),
	UPDATED_TIME  TIMESTAMP,
	UPDATED_BY    VARCHAR2(50),
	CREATED_IP    VARCHAR2(45),
	UPDATED_IP    VARCHAR2(45),
	CONSTRAINT PK_MENU_ID PRIMARY KEY (MENU_ID),
	CONSTRAINT CHK_MENU_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);
/

CREATE TABLE AIRLINE_CITY_MSTR_TBL (
    CITY_ID         NUMBER(10),
    CITY_NAME       VARCHAR2(100) NOT NULL,
    STATE_NAME      VARCHAR2(100),
    COUNTRY_NAME    VARCHAR2(100),
    IS_ACTIVE       CHAR(1) DEFAULT 'Y',
    CREATED_TIME    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY      VARCHAR2(10),
    UPDATED_TIME    TIMESTAMP,
    UPDATED_BY      VARCHAR2(10),
    CREATED_IP      VARCHAR2(100),
    UPDATED_IP      VARCHAR2(100),
    CONSTRAINT PK_CITY_ID PRIMARY KEY (CITY_ID)
);
/

CREATE TABLE AIRLINE_ROLE_MENU_MAP_TBL (
	ROW_NO        NUMBER(35) GENERATED ALWAYS AS IDENTITY,
	ROLE_ID       NUMBER(10),
	MENU_ID       NUMBER(10),
	IS_ACTIVE     CHAR(1) DEFAULT 'Y',
	CREATED_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP,
	CREATED_BY    VARCHAR2(10),
	UPDATED_TIME  TIMESTAMP,
	UPDATED_BY    VARCHAR2(10),
	CREATED_IP    VARCHAR2(100),
	UPDATED_IP    VARCHAR2(100),      
	CONSTRAINT AIRLINE_ROLE_MENU_MAP_TBL_PK_ROW_NO PRIMARY KEY (ROW_NO),
	CONSTRAINT AIRLINE_ROLE_MENU_MAP_TBL_UK UNIQUE (ROLE_ID, MENU_ID)
);
/

CREATE TABLE AIRLINE_AIRPORT_MSTR_TBL (
    AIRPORT_ID      NUMBER(10),
    AIRPORT_NAME    VARCHAR2(200) NOT NULL,
    AIRPORT_CODE    VARCHAR2(10) NOT NULL,
    CITY_ID         NUMBER(10),
    IS_ACTIVE       CHAR(1) DEFAULT 'Y',
    CREATED_TIME    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY      VARCHAR2(10),
    UPDATED_TIME    TIMESTAMP,
    UPDATED_BY      VARCHAR2(10),
    CREATED_IP      VARCHAR2(100),
    UPDATED_IP      VARCHAR2(100),
    CONSTRAINT PK_AIRPORT_ID PRIMARY KEY (AIRPORT_ID),
    CONSTRAINT UK_AIRPORT_CODE UNIQUE (AIRPORT_CODE),
    CONSTRAINT FK_AIRPORT_CITY FOREIGN KEY (CITY_ID) REFERENCES AIRLINE_CITY_MSTR_TBL(CITY_ID)
);
/

CREATE TABLE AIRLINE_FLIGHT_COMPANY_MSTR_TBL (
    COMPANY_ID      NUMBER(10),
    COMPANY_NAME    VARCHAR2(200) NOT NULL,
    COMPANY_CODE    VARCHAR2(20),
    IS_ACTIVE       CHAR(1) DEFAULT 'Y',
    CREATED_TIME    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY      VARCHAR2(10),
    UPDATED_TIME    TIMESTAMP,
    UPDATED_BY      VARCHAR2(10),
    CREATED_IP      VARCHAR2(100),
    UPDATED_IP      VARCHAR2(100),
    CONSTRAINT PK_COMPANY_ID PRIMARY KEY (COMPANY_ID)
);
/

CREATE TABLE AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL (
    PASSENGER_ID        NUMBER(10),
    PASSENGER_NAME      VARCHAR2(200) NOT NULL,
    GENDER              CHAR(1),
    DOB                 DATE,
    MOBILE_NO           NUMBER(10),
    EMAIL_ID            VARCHAR2(200),
    PASSPORT_NO         VARCHAR2(50),
    MEMBER_TIER         VARCHAR2(50) DEFAULT 'VIP Platinum',
    PROFILE_IMG         VARCHAR2(2000),
    IS_ACTIVE           CHAR(1) DEFAULT 'Y',
    CREATED_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY          VARCHAR2(10),
    UPDATED_TIME        TIMESTAMP,
    UPDATED_BY          VARCHAR2(10),
    CREATED_IP          VARCHAR2(100),
    UPDATED_IP          VARCHAR2(100),
    CONSTRAINT PK_PASSENGER_ID PRIMARY KEY (PASSENGER_ID)
);
/

CREATE TABLE AIRLINE_FLIGHT_MSTR_TBL (
    FLIGHT_ID          NUMBER(10),
    FLIGHT_NO          VARCHAR2(20) NOT NULL,
    COMPANY_ID         NUMBER(10) NOT NULL,
    FLIGHT_NAME        VARCHAR2(100),
    TOTAL_SEATS        NUMBER(5) DEFAULT 180 NOT NULL,
    IS_ACTIVE          CHAR(1) DEFAULT 'Y',
    CREATED_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY         VARCHAR2(20),
    UPDATED_TIME       TIMESTAMP,
    UPDATED_BY         VARCHAR2(20),
    CREATED_IP         VARCHAR2(100),
    UPDATED_IP         VARCHAR2(100),
    CONSTRAINT PK_FLIGHT_ID PRIMARY KEY (FLIGHT_ID),
    CONSTRAINT UK_FLIGHT_NO UNIQUE (FLIGHT_NO),
    CONSTRAINT FK_FLIGHT_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES AIRLINE_FLIGHT_COMPANY_MSTR_TBL(COMPANY_ID),
    CONSTRAINT CHK_FLIGHT_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE AIRLINE_FLIGHT_SEAT_MSTR_TBL (
    SEAT_ID            NUMBER(10),
    FLIGHT_ID          NUMBER(10) NOT NULL,
    SEAT_NO            VARCHAR2(10) NOT NULL,
    SEAT_ROW           NUMBER(3) NOT NULL,
    SEAT_COL           CHAR(1) NOT NULL,
    SEAT_CLASS         VARCHAR2(20) DEFAULT 'ECONOMY',
    SEAT_TYPE          VARCHAR2(20) DEFAULT 'REGULAR',
    PRICE_SURCHARGE    NUMBER(10,2) DEFAULT 0.00,
    IS_ACTIVE          CHAR(1) DEFAULT 'Y',
    CREATED_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY         VARCHAR2(20),
    CONSTRAINT PK_SEAT_ID PRIMARY KEY (SEAT_ID),
    CONSTRAINT FK_SEAT_FLIGHT FOREIGN KEY (FLIGHT_ID) REFERENCES AIRLINE_FLIGHT_MSTR_TBL(FLIGHT_ID),
    CONSTRAINT UK_FLIGHT_SEAT_NO UNIQUE (FLIGHT_ID, SEAT_NO)
);
/

CREATE TABLE AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL (
    DYNAMIC_PRICE_ID      NUMBER(10),
    FLIGHT_ID             NUMBER(10),
    SOURCE_AIRPORT_ID     NUMBER(10),
    DEST_AIRPORT_ID       NUMBER(10),
    FLIGHT_DATE           DATE,
    DEPARTURE_TIME        TIMESTAMP,
    ARRIVAL_TIME          TIMESTAMP,
    TOTAL_SEATS           NUMBER(5),
    AVAILABLE_SEATS       NUMBER(5),
    CURRENT_PRICE         NUMBER(10,2),
    IS_ACTIVE             CHAR(1) DEFAULT 'Y',
    CREATED_TIME          TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY            VARCHAR2(20),
    UPDATED_TIME          TIMESTAMP,
    UPDATED_BY            VARCHAR2(20),
    CREATED_IP            VARCHAR2(100),
    UPDATED_IP            VARCHAR2(100),
    CONSTRAINT PK_DYNAMIC_PRICE_ID PRIMARY KEY (DYNAMIC_PRICE_ID),
    CONSTRAINT FK_DP_FLIGHT FOREIGN KEY (FLIGHT_ID) REFERENCES AIRLINE_FLIGHT_MSTR_TBL(FLIGHT_ID),
    CONSTRAINT FK_DP_SOURCE FOREIGN KEY (SOURCE_AIRPORT_ID) REFERENCES AIRLINE_AIRPORT_MSTR_TBL(AIRPORT_ID),
    CONSTRAINT FK_DP_DEST FOREIGN KEY (DEST_AIRPORT_ID) REFERENCES AIRLINE_AIRPORT_MSTR_TBL(AIRPORT_ID)
);
/

CREATE TABLE AIRLINE_FLIGHT_SEAT_BOOKING_TBL (
    SEAT_BOOKING_ID        NUMBER(10),
    DYNAMIC_PRICE_ID       NUMBER(10) NOT NULL,
    SEAT_NO                VARCHAR2(10) NOT NULL,
    STATUS                 VARCHAR2(20) DEFAULT 'AVAILABLE',
    BOOKING_ID             NUMBER(10),
    BOOKED_BY_PASSENGER_ID NUMBER(10),
    FINAL_SEAT_PRICE       NUMBER(10,2),
    UPDATED_TIME           TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_SEAT_BOOKING_ID PRIMARY KEY (SEAT_BOOKING_ID),
    CONSTRAINT FK_SB_DYNAMIC_PRICE FOREIGN KEY (DYNAMIC_PRICE_ID) REFERENCES AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL(DYNAMIC_PRICE_ID),
    CONSTRAINT UK_DP_SEAT_NO UNIQUE (DYNAMIC_PRICE_ID, SEAT_NO)
);
/

CREATE TABLE AIRLINE_TICKET_BOOKING_TRANSACTION_TBL (
    BOOKING_ID             NUMBER(10),
    PASSENGER_ID           NUMBER(10),
    DYNAMIC_PRICE_ID       NUMBER(10),
    PNR_NO                 VARCHAR2(20),
    SEAT_NO                VARCHAR2(10),
    BOOKING_STATUS         VARCHAR2(20),
    PAYMENT_STATUS         VARCHAR2(20),
    BOOKING_AMOUNT         NUMBER(10,2),
    BOOKING_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_ACTIVE              CHAR(1) DEFAULT 'Y',
    CREATED_TIME           TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY             VARCHAR2(20),
    UPDATED_TIME           TIMESTAMP,
    UPDATED_BY             VARCHAR2(20),
    CREATED_IP             VARCHAR2(100),
    UPDATED_IP             VARCHAR2(100),
    CONSTRAINT PK_BOOKING_ID PRIMARY KEY (BOOKING_ID),
    CONSTRAINT FK_BOOKING_PASSENGER FOREIGN KEY (PASSENGER_ID) REFERENCES AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL(PASSENGER_ID),
    CONSTRAINT FK_BOOKING_DYNAMIC_PRICE FOREIGN KEY (DYNAMIC_PRICE_ID) REFERENCES AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL(DYNAMIC_PRICE_ID),
    CONSTRAINT UK_PNR_NO UNIQUE (PNR_NO)
);
/

CREATE TABLE AIRLINE_ERROR_LOG_TBL (
    ROW_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ERROR_DESC VARCHAR2(4000),
    CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

CREATE TABLE AIRLINE_PARAMETER_LOG_TBL (
    ROW_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PARAM VARCHAR2(4000),
    CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

-- =============================================================================
-- 2. SEQUENCES
-- =============================================================================

CREATE SEQUENCE AIRLINE_USER_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 10000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_ROLE_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 11000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_MENU_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 12000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_CITY_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 13000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_AIRPORT_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 14000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_FLIGHT_COMPANY_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 15000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 16000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_PASSENGERS_REGD_FORM_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 17000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_FLIGHT_MSTR_TBL_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 18000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_FLIGHT_SEAT_MSTR_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 20000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_FLIGHT_SEAT_BOOKING_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 21000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE AIRLINE_TICKET_BOOKING_TRANSACTION_SEQ MINVALUE 1 MAXVALUE 90000001 INCREMENT BY 1 START WITH 19000001 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

-- =============================================================================
-- 3. INITIAL SEED DATA
-- =============================================================================

INSERT INTO AIRLINE_USER_MSTR_TBL (
	USER_ID, USERNAME, MOBILENO, PASSWD, MPIN, OTP, CREATED_BY, PASSPORT_IMG
) VALUES (
	AIRLINE_USER_MSTR_SEQ.NEXTVAL, 'dushmantadas@aos.com', 7008233179, 'das@123', 1111, NULL, 'DUSHMANTA',
	'C:\SOFTWARE\AOS\frontend\static\passport\das passport.jpg'
);

INSERT INTO AIRLINE_USER_MSTR_TBL (
	USER_ID, USERNAME, MOBILENO, PASSWD, MPIN, OTP, CREATED_BY, PASSPORT_IMG
) VALUES (
	AIRLINE_USER_MSTR_SEQ.NEXTVAL, 'darshildas@aos.com', 9861017552, 'das@123', 1111, NULL, 'DARSHIL',
	'C:\SOFTWARE\AOS\frontend\static\passport\OMM_PASSPORT_PHOTO.jpeg'
);
COMMIT;

INSERT INTO AIRLINE_ROLE_MSTR_TBL (ROLE_ID, ROLE_NAME, CREATED_BY, CREATED_IP)
VALUES (AIRLINE_ROLE_MSTR_SEQ.NEXTVAL, 'ADMIN', 'DARSHIL', '100.125.49.24');

INSERT INTO AIRLINE_ROLE_MSTR_TBL (ROLE_ID, ROLE_NAME, CREATED_BY, CREATED_IP)
VALUES (AIRLINE_ROLE_MSTR_SEQ.NEXTVAL, 'OPERATOR', 'DARSHIL', '100.125.49.24');

-- Insert PASSENGER Role (using Sequence)
INSERT INTO AIRLINE_ROLE_MSTR_TBL (
    ROLE_ID,
    ROLE_NAME,
    IS_ACTIVE,
    CREATED_BY,
    CREATED_IP
) VALUES (
    AIRLINE_ROLE_MSTR_SEQ.NEXTVAL,
    'PASSENGER',
    'Y',
    'DUSHMANTA',
    '127.0.0.1'
);
COMMIT;

INSERT INTO AIRLINE_USER_MSTR_TBL (
	USER_ID, USERNAME, MOBILENO, PASSWD, MPIN, OTP, CREATED_BY, PASSPORT_IMG
) VALUES (
	AIRLINE_USER_MSTR_SEQ.NEXTVAL, 'passenger@aos.com', 9876543210, 'pass@123', 1234, NULL, 'SYSTEM',
	NULL
);
COMMIT;

INSERT INTO AIRLINE_USER_ROLE_MAP_TBL (USER_ID, ROLE_ID, CREATED_BY, CREATED_IP)
VALUES (10000001, 11000001, 'DUSHMANTA', '100.125.49.24');  

INSERT INTO AIRLINE_USER_ROLE_MAP_TBL (USER_ID, ROLE_ID, CREATED_BY, CREATED_IP)
VALUES (10000002, 11000002, 'DUSHMANTA', '100.125.49.24');  

INSERT INTO AIRLINE_USER_ROLE_MAP_TBL (USER_ID, ROLE_ID, CREATED_BY, CREATED_IP)
SELECT 
    (SELECT USER_ID FROM AIRLINE_USER_MSTR_TBL WHERE LOWER(USERNAME) = 'passenger@aos.com' AND ROWNUM = 1),
    (SELECT ROLE_ID FROM AIRLINE_ROLE_MSTR_TBL WHERE UPPER(ROLE_NAME) = 'PASSENGER' AND ROWNUM = 1),
    'Y',
    'DUSHMANTA',
    '127.0.0.1'
FROM DUAL;
COMMIT;

INSERT INTO AIRLINE_MENU_MSTR_TBL (MENU_ID, MENU_NAME, CREATED_BY, CREATED_IP)
VALUES (AIRLINE_MENU_MSTR_SEQ.NEXTVAL, 'CREATE USER', 'DARSHIL', '100.125.49.24');

INSERT INTO AIRLINE_MENU_MSTR_TBL (MENU_ID, MENU_NAME, CREATED_BY, CREATED_IP)
VALUES (AIRLINE_MENU_MSTR_SEQ.NEXTVAL, 'ASSIGN ROLE TO USER', 'DUSHMANTA', '100.125.49.24');
COMMIT;

INSERT INTO AIRLINE_ROLE_MENU_MAP_TBL (ROLE_ID, MENU_ID, CREATED_BY, CREATED_IP)
VALUES (11000001, 12000001, 'DUSHMANTA', '100.125.49.24');  

INSERT INTO AIRLINE_ROLE_MENU_MAP_TBL (ROLE_ID, MENU_ID, CREATED_BY, CREATED_IP)
VALUES (11000001, 12000002, 'DUSHMANTA', '100.125.49.24');  

-- Map PASSENGER Role to Customer Menus (REGISTER CUSTOMER & SEAT BOOKING)
INSERT INTO AIRLINE_ROLE_MENU_MAP_TBL (ROLE_ID, MENU_ID, IS_ACTIVE, CREATED_BY, CREATED_IP)
SELECT 
    (SELECT ROLE_ID FROM AIRLINE_ROLE_MSTR_TBL WHERE UPPER(ROLE_NAME) = 'PASSENGER' AND ROWNUM = 1),
    MENU_ID,
    'Y',
    'DUSHMANTA',
    '127.0.0.1'
FROM AIRLINE_MENU_MSTR_TBL
WHERE UPPER(MENU_NAME) IN ('REGISTER CUSTOMER', 'SEAT BOOKING');
COMMIT;

-- =============================================================================
-- 4. STORED PROCEDURES
-- =============================================================================

CREATE OR REPLACE PROCEDURE AIRLINE_AIRPORT_CREATE_USP (
    P_AIRPORTNAME IN VARCHAR2,
    P_AIRPORTCODE IN VARCHAR2,
    P_CITY_ID     IN VARCHAR2,
    P_ACTION      IN VARCHAR2,
    P_CURSOR      OUT SYS_REFCURSOR,
    P_DATA        OUT VARCHAR2
)
IS
    V_COUNT NUMBER;
BEGIN
    IF P_ACTION = 'DROPDOWN' THEN
        OPEN P_CURSOR FOR
            SELECT CITY_ID, CITY_NAME
            FROM AIRLINE_CITY_MSTR_TBL
            WHERE IS_ACTIVE = 'Y'
            ORDER BY CITY_NAME;

        P_DATA := 'CITY LIST FETCHED SUCCESSFULLY';

    ELSIF P_ACTION = 'SELECT' THEN
        OPEN P_CURSOR FOR
            SELECT A.AIRPORT_ID, A.AIRPORT_NAME, A.AIRPORT_CODE, A.CITY_ID, C.CITY_NAME, C.COUNTRY_NAME
            FROM AIRLINE_AIRPORT_MSTR_TBL A
            LEFT JOIN AIRLINE_CITY_MSTR_TBL C ON A.CITY_ID = C.CITY_ID
            WHERE A.IS_ACTIVE = 'Y' OR A.IS_ACTIVE IS NULL
            ORDER BY A.AIRPORT_NAME;

        P_DATA := 'AIRPORT LIST FETCHED SUCCESSFULLY';

    ELSIF P_ACTION = 'INSERT' THEN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM AIRLINE_AIRPORT_MSTR_TBL
        WHERE UPPER(AIRPORT_NAME) = UPPER(P_AIRPORTNAME)
          AND UPPER(AIRPORT_CODE) = UPPER(P_AIRPORTCODE);

        IF V_COUNT > 0 THEN
            P_DATA := 'THE AIRPORT IS ALREADY THERE';
        ELSE
            INSERT INTO AIRLINE_AIRPORT_MSTR_TBL
                (AIRPORT_ID, AIRPORT_NAME, AIRPORT_CODE, CITY_ID, CREATED_BY, CREATED_IP)
            VALUES
                (AIRLINE_AIRPORT_MSTR_SEQ.NEXTVAL,
                 UPPER(P_AIRPORTNAME),
                 UPPER(P_AIRPORTCODE),
                 TO_NUMBER(P_CITY_ID),
                 'DUSHMANTA',
                 '100.125.49.24');

            P_DATA := 'AIRPORT INSERTED SUCCESSFULLY';
            COMMIT;
        END IF;

    ELSE
        P_DATA := 'INVALID ACTION';
    END IF;
END AIRLINE_AIRPORT_CREATE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ASSIGN_OR_UPDATE_ROLE_TO_USER_USP (
    P_USER_ID      IN NUMBER,
    P_ROLE_ID      IN NUMBER,
    P_CREATED_BY   IN VARCHAR2,
    P_CREATED_IP   IN VARCHAR2,
    P_DATA         OUT VARCHAR2
)
IS
    V_ROLE_COUNT NUMBER;
    V_USER_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_ROLE_COUNT
    FROM AIRLINE_ROLE_MSTR_TBL
    WHERE ROLE_ID = P_ROLE_ID
      AND IS_ACTIVE = 'Y';

    IF V_ROLE_COUNT = 0 THEN
        P_DATA := 'ROLE IS NOT ACTIVE';
        RETURN;
    END IF;

    SELECT COUNT(*)
    INTO V_USER_COUNT
    FROM AIRLINE_USER_ROLE_MAP_TBL
    WHERE USER_ID = P_USER_ID;

    IF V_USER_COUNT > 0 THEN
        UPDATE AIRLINE_USER_ROLE_MAP_TBL
        SET ROLE_ID      = P_ROLE_ID,
            UPDATED_TIME = SYSTIMESTAMP,
            UPDATED_BY   = P_CREATED_BY,
            UPDATED_IP   = P_CREATED_IP
        WHERE USER_ID = P_USER_ID;
        P_DATA := 'ROLE UPDATED SUCCESSFULLY';
    ELSE
        INSERT INTO AIRLINE_USER_ROLE_MAP_TBL
            (USER_ID, ROLE_ID, IS_ACTIVE, CREATED_BY, CREATED_IP)
        VALUES
            (P_USER_ID, P_ROLE_ID, 'Y', P_CREATED_BY, P_CREATED_IP);
        P_DATA := 'ROLE ASSIGNED SUCCESSFULLY';
    END IF;
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_DATA := SQLERRM;
END AIRLINE_ASSIGN_OR_UPDATE_ROLE_TO_USER_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ASSIGN_ROLE_SCREEN_USP (
    P_USERS OUT SYS_REFCURSOR,
    P_ROLES OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN P_USERS FOR
        SELECT USER_ID, USERNAME, MOBILENO
        FROM AIRLINE_USER_MSTR_TBL
        WHERE IS_ACTIVE = 'Y'
        ORDER BY USERNAME;

    OPEN P_ROLES FOR
        SELECT ROLE_ID, ROLE_NAME
        FROM AIRLINE_ROLE_MSTR_TBL
        WHERE IS_ACTIVE = 'Y'
        ORDER BY ROLE_NAME;
END AIRLINE_ASSIGN_ROLE_SCREEN_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_CHECK_MOBILE_USP (
    P_MOBILENO IN NUMBER,
    P_COUNT    OUT NUMBER
)
IS
BEGIN
    SELECT COUNT(*) INTO P_COUNT
    FROM AIRLINE_USER_MSTR_TBL
    WHERE MOBILENO = P_MOBILENO;
END AIRLINE_CHECK_MOBILE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_CITY_CREATE_USP (
    P_CITYNAME    IN VARCHAR2,
    P_STATENAME   IN VARCHAR2,
    P_COUNTRYNAME IN VARCHAR2,
    P_ACTION      IN VARCHAR2,
    P_CURSOR      OUT SYS_REFCURSOR,
    P_DATA        OUT VARCHAR2
)
IS
    V_COUNT NUMBER;
BEGIN
    IF P_ACTION = 'INSERT' THEN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM AIRLINE_CITY_MSTR_TBL
        WHERE CITY_NAME = UPPER(P_CITYNAME)
          AND STATE_NAME = UPPER(P_STATENAME)
          AND COUNTRY_NAME = UPPER(P_COUNTRYNAME);

        IF V_COUNT > 0 THEN
            P_DATA := 'THE CITY IS ALREADY THERE';
        ELSE
            INSERT INTO AIRLINE_CITY_MSTR_TBL
                (CITY_ID, CITY_NAME, STATE_NAME, COUNTRY_NAME, CREATED_BY, CREATED_IP)
            VALUES
                (AIRLINE_CITY_MSTR_SEQ.NEXTVAL, UPPER(P_CITYNAME), UPPER(P_STATENAME), UPPER(P_COUNTRYNAME), 'DUSHMANTA', '100.125.49.24');

            P_DATA := 'CITY INSERTED SUCCESSFULLY';
            COMMIT;
        END IF;

        OPEN P_CURSOR FOR
            SELECT CITY_NAME, STATE_NAME, COUNTRY_NAME
            FROM AIRLINE_CITY_MSTR_TBL
            ORDER BY CITY_NAME;

    ELSIF P_ACTION = 'SELECT' THEN
        OPEN P_CURSOR FOR
            SELECT CITY_NAME, STATE_NAME, COUNTRY_NAME
            FROM AIRLINE_CITY_MSTR_TBL
            ORDER BY CITY_NAME;
        P_DATA := 'SELECT SUCCESSFUL';

    ELSE
        P_DATA := 'INVALID ACTION';
    END IF;   
END AIRLINE_CITY_CREATE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_FIND_ROLE_USER_USP (
    P_USER_ID IN NUMBER,
    P_RECORD OUT SYS_REFCURSOR
) IS
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_FIND_ROLE_USER_USP P_USER_ID=' || P_USER_ID);
    COMMIT; 

    OPEN P_RECORD FOR
        SELECT R.ROLE_ID, R.ROLE_NAME 
        FROM AIRLINE_ROLE_MSTR_TBL R
        JOIN AIRLINE_USER_ROLE_MAP_TBL MAP ON R.ROLE_ID = MAP.ROLE_ID
        WHERE MAP.USER_ID = P_USER_ID;
END AIRLINE_FIND_ROLE_USER_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_FLIGHT_COMPANY_CREATE_USP (
    P_COMPANYNAME IN VARCHAR2,
    P_COMPANYCODE IN VARCHAR2,
    P_ACTION      IN VARCHAR2,
    P_CURSOR      OUT SYS_REFCURSOR,
    P_DATA        OUT VARCHAR2
)
IS
    V_COUNT NUMBER;
BEGIN
    IF UPPER(P_ACTION) = 'INSERT' THEN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM AIRLINE_FLIGHT_COMPANY_MSTR_TBL
        WHERE COMPANY_NAME = UPPER(P_COMPANYNAME)
          AND COMPANY_CODE = UPPER(P_COMPANYCODE);

        IF V_COUNT > 0 THEN
            P_DATA := 'THE FLIGHT COMPANY ALREADY EXISTS';
        ELSE
            INSERT INTO AIRLINE_FLIGHT_COMPANY_MSTR_TBL
                (COMPANY_ID, COMPANY_NAME, COMPANY_CODE, CREATED_BY, CREATED_IP)
            VALUES
                (AIRLINE_FLIGHT_COMPANY_MSTR_SEQ.NEXTVAL, UPPER(P_COMPANYNAME), UPPER(P_COMPANYCODE), 'DUSHMANTA', '100.125.49.24');

            P_DATA := 'FLIGHT COMPANY CREATED SUCCESSFULLY';
        END IF;

    ELSIF UPPER(P_ACTION) = 'DROPDOWN' THEN
        OPEN P_CURSOR FOR
            SELECT COMPANY_ID, COMPANY_NAME, COMPANY_CODE
            FROM AIRLINE_FLIGHT_COMPANY_MSTR_TBL
            WHERE IS_ACTIVE = 'Y'
            ORDER BY COMPANY_NAME;

        P_DATA := 'FLIGHT COMPANY DATA FETCHED SUCCESSFULLY';

    ELSE
        P_DATA := 'INVALID ACTION';
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        P_DATA := SQLERRM;
END AIRLINE_FLIGHT_COMPANY_CREATE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_ACTIVE_CREW_COUNT_USP (
    p_active_cnt OUT NUMBER
) IS
BEGIN
    SELECT COUNT(*) INTO p_active_cnt FROM AIRLINE_USER_MSTR_TBL WHERE IS_ACTIVE = 'Y';
END AIRLINE_GET_ACTIVE_CREW_COUNT_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_ALL_USERS_USP (
    P_RESULT OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULT FOR
        SELECT  u.USER_ID,
                u.USERNAME,
                u.MOBILENO,
                u.PASSPORT_IMG,
                u.IS_ACTIVE,
                r.ROLE_NAME
        FROM    AIRLINE_USER_MSTR_TBL u
        LEFT JOIN AIRLINE_USER_ROLE_MAP_TBL urm
               ON u.USER_ID = urm.USER_ID
              AND urm.IS_ACTIVE = 'Y'
        LEFT JOIN AIRLINE_ROLE_MSTR_TBL r
               ON urm.ROLE_ID = r.ROLE_ID
              AND r.IS_ACTIVE = 'Y'
        ORDER BY u.USER_ID;
EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END AIRLINE_GET_ALL_USERS_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_MENU_DROP_DOWN_MAPPED_USP (
    P_ROLE_ID IN VARCHAR2,
    P_RECORD  OUT SYS_REFCURSOR
)
IS
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_GET_MENU_DROP_DOWN_MAPPED_USP P_ROLE_ID = ' || NVL(P_ROLE_ID, 'NULL'));
    COMMIT;

    OPEN P_RECORD FOR
        SELECT DISTINCT MM.MENU_ID, MM.MENU_NAME  
        FROM AIRLINE_MENU_MSTR_TBL MM 
        WHERE MM.IS_ACTIVE = 'Y'
          AND MM.MENU_ID IN (
              SELECT MM_MAP.MENU_ID
              FROM AIRLINE_ROLE_MENU_MAP_TBL MM_MAP 
              JOIN AIRLINE_MENU_MSTR_TBL MENU ON MENU.MENU_ID = MM_MAP.MENU_ID
              WHERE MM_MAP.ROLE_ID = P_ROLE_ID
          );
END AIRLINE_GET_MENU_DROP_DOWN_MAPPED_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_MENU_DROP_DOWN_NOTMAPPED_USP (
    P_ROLE_ID IN VARCHAR2,
    P_RECORD  OUT SYS_REFCURSOR
)
IS
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_GET_MENU_DROP_DOWN_NOTMAPPED_USP P_ROLE_ID = ' || NVL(P_ROLE_ID, 'NULL'));
    COMMIT;

    OPEN P_RECORD FOR
        SELECT DISTINCT MM.MENU_ID, MM.MENU_NAME  
        FROM AIRLINE_MENU_MSTR_TBL MM 
        WHERE MM.IS_ACTIVE = 'Y'
          AND MM.MENU_ID NOT IN (
              SELECT MM_MAP.MENU_ID
              FROM AIRLINE_ROLE_MENU_MAP_TBL MM_MAP 
              JOIN AIRLINE_MENU_MSTR_TBL MENU ON MENU.MENU_ID = MM_MAP.MENU_ID
              WHERE MM_MAP.ROLE_ID = P_ROLE_ID
          );
END AIRLINE_GET_MENU_DROP_DOWN_NOTMAPPED_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_MENU_USP (
    P_USERNAME IN VARCHAR2,
    P_RECORD   OUT SYS_REFCURSOR
)
IS
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_GET_MENU_USP P_USERNAME = ' || P_USERNAME);
    COMMIT;

    OPEN P_RECORD FOR
        SELECT DISTINCT MM.MENU_NAME 
        FROM AIRLINE_USER_MSTR_TBL U
        JOIN AIRLINE_USER_ROLE_MAP_TBL UR ON U.USER_ID = UR.USER_ID AND (UR.IS_ACTIVE = 'Y' OR UR.IS_ACTIVE IS NULL)
        JOIN AIRLINE_ROLE_MSTR_TBL R ON UR.ROLE_ID = R.ROLE_ID AND (R.IS_ACTIVE = 'Y' OR R.IS_ACTIVE IS NULL)
        JOIN AIRLINE_ROLE_MENU_MAP_TBL RM ON R.ROLE_ID = RM.ROLE_ID AND (RM.IS_ACTIVE = 'Y' OR RM.IS_ACTIVE IS NULL)
        JOIN AIRLINE_MENU_MSTR_TBL MM ON RM.MENU_ID = MM.MENU_ID AND (MM.IS_ACTIVE = 'Y' OR MM.IS_ACTIVE IS NULL)
        WHERE LOWER(U.USERNAME) = LOWER(P_USERNAME)
        ORDER BY MM.MENU_NAME; 
END AIRLINE_GET_MENU_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_PASSPORT_IMG_USP (
    P_USER_ID       IN NUMBER,
    P_PASSPORT_IMG  OUT VARCHAR2
)
IS
BEGIN
    SELECT PASSPORT_IMG INTO P_PASSPORT_IMG
    FROM AIRLINE_USER_MSTR_TBL
    WHERE USER_ID = P_USER_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_PASSPORT_IMG := NULL;
END AIRLINE_GET_PASSPORT_IMG_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_ROLE_USP (
    P_USERNAME IN VARCHAR2,
    P_RECORD OUT SYS_REFCURSOR
) IS
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_GET_ROLE_USP P_USERNAME=' || NVL(P_USERNAME, 'NULL'));
    COMMIT;

    OPEN P_RECORD FOR
        SELECT ROLE_ID, ROLE_NAME
        FROM AIRLINE_ROLE_MSTR_TBL
        ORDER BY ROLE_NAME;
END AIRLINE_GET_ROLE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_USER_PROFILE_FULL_USP (
    P_USER_IDENTIFIER IN VARCHAR2,
    P_LOGIN_MODE      IN VARCHAR2,
    P_RESULT          OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULT FOR
        SELECT  u.USER_ID,
                u.USERNAME,
                u.MOBILENO,
                u.PASSPORT_IMG,
                u.IS_ACTIVE,
                NVL(r.ROLE_NAME, 'USER')
        FROM    AIRLINE_USER_MSTR_TBL u
        LEFT JOIN AIRLINE_USER_ROLE_MAP_TBL urm
               ON u.USER_ID = urm.USER_ID
              AND (urm.IS_ACTIVE = 'Y' OR urm.IS_ACTIVE IS NULL)
        LEFT JOIN AIRLINE_ROLE_MSTR_TBL r
               ON urm.ROLE_ID = r.ROLE_ID
              AND (r.IS_ACTIVE = 'Y' OR r.IS_ACTIVE IS NULL)
        WHERE   ( P_LOGIN_MODE = 'U' AND (LOWER(u.USERNAME) = LOWER(P_USER_IDENTIFIER) OR LOWER(u.USERNAME) LIKE LOWER(P_USER_IDENTIFIER || '@%') OR TO_CHAR(u.USER_ID) = P_USER_IDENTIFIER) )
           OR   ( P_LOGIN_MODE <> 'U' AND (TO_CHAR(u.MOBILENO) = P_USER_IDENTIFIER OR TO_CHAR(u.USER_ID) = P_USER_IDENTIFIER) )
        ORDER BY u.USER_ID;
EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END AIRLINE_GET_USER_PROFILE_FULL_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_USER_PROFILE_USP (
    P_USER_IDENTIFIER IN VARCHAR2,
    P_LOGIN_MODE      IN VARCHAR2,
    P_USER_ID         OUT NUMBER,
    P_USERNAME        OUT VARCHAR2,
    P_PASSPORT_IMG    OUT VARCHAR2,
    P_ROLE_NAME       OUT VARCHAR2
)
IS
BEGIN
    IF P_LOGIN_MODE = 'U' THEN
        SELECT USER_ID, USERNAME, PASSPORT_IMG
        INTO P_USER_ID, P_USERNAME, P_PASSPORT_IMG
        FROM AIRLINE_USER_MSTR_TBL
        WHERE LOWER(USERNAME) = LOWER(P_USER_IDENTIFIER);
    ELSE
        SELECT USER_ID, USERNAME, PASSPORT_IMG
        INTO P_USER_ID, P_USERNAME, P_PASSPORT_IMG
        FROM AIRLINE_USER_MSTR_TBL
        WHERE MOBILENO = TO_NUMBER(P_USER_IDENTIFIER);
    END IF;

    BEGIN
        SELECT r.ROLE_NAME
        INTO P_ROLE_NAME
        FROM AIRLINE_USER_ROLE_MAP_TBL urm
        JOIN AIRLINE_ROLE_MSTR_TBL r ON urm.ROLE_ID = r.ROLE_ID
        WHERE urm.USER_ID = P_USER_ID
          AND urm.IS_ACTIVE = 'Y'
          AND r.IS_ACTIVE = 'Y';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_ROLE_NAME := NULL;
    END;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_USER_ID := NULL;
        P_USERNAME := NULL;
        P_PASSPORT_IMG := NULL;
        P_ROLE_NAME := NULL;
END AIRLINE_GET_USER_PROFILE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_USER_ROLE_USP (
    P_USER_ID IN NUMBER,
    P_RECORD OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN P_RECORD FOR
        SELECT U.USER_ID, U.USERNAME, R.ROLE_ID, R.ROLE_NAME
        FROM AIRLINE_USER_MSTR_TBL U
        JOIN AIRLINE_USER_ROLE_MAP_TBL UR ON U.USER_ID = UR.USER_ID
        JOIN AIRLINE_ROLE_MSTR_TBL R ON UR.ROLE_ID = R.ROLE_ID
        WHERE U.USER_ID = P_USER_ID
          AND UR.IS_ACTIVE = 'Y';
END AIRLINE_GET_USER_ROLE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_USER_USP (
    P_USERNAME IN VARCHAR2,
    P_RECORD   OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN P_RECORD FOR
        SELECT USER_ID, USERNAME FROM AIRLINE_USER_MSTR_TBL;
END AIRLINE_GET_USER_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_MENU_MSTR_INSERT_USP (
    P_MENU_NAME IN VARCHAR2,
    P_DATA      OUT VARCHAR2
)
IS
    V_ERROR VARCHAR2(4000);
    V_COUNT NUMBER;
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_MENU_MSTR_INSERT_USP P_MENU_NAME = ' || P_MENU_NAME);
    COMMIT;

    SELECT COUNT(*)
    INTO V_COUNT
    FROM AIRLINE_MENU_MSTR_TBL
    WHERE MENU_NAME = P_MENU_NAME;

    IF V_COUNT > 0 THEN
        P_DATA := 'MENU ALREADY EXISTS';
    ELSE
        INSERT INTO AIRLINE_MENU_MSTR_TBL (MENU_ID, MENU_NAME)
        VALUES (AIRLINE_MENU_MSTR_SEQ.NEXTVAL, P_MENU_NAME);
        P_DATA := 'MENU CREATED SUCCESSFULLY';
    END IF;
EXCEPTION
    WHEN OTHERS THEN 
        V_ERROR := SQLERRM || ', ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || ', SPNAME AIRLINE_MENU_MSTR_INSERT_USP P_MENU_NAME ' || P_MENU_NAME;
        ROLLBACK;
        INSERT INTO AIRLINE_ERROR_LOG_TBL(ERROR_DESC) VALUES (V_ERROR);
        COMMIT;
END AIRLINE_MENU_MSTR_INSERT_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_MENU_OPERATION_USP (
    P_MENU_ID      IN VARCHAR2,
    P_MENUNAME     IN VARCHAR2,
    P_ACTION       IN VARCHAR2,
    P_DATA_CREATE  OUT VARCHAR2,
    P_DATA_DELETE  OUT VARCHAR2,
    P_CURSOR       OUT SYS_REFCURSOR
)
IS
    V_COUNT1 NUMBER := 0;
    V_COUNT2 NUMBER := 0;
BEGIN
    IF UPPER(P_ACTION) = 'CREATE' THEN
        SELECT COUNT(*) INTO V_COUNT1 FROM AIRLINE_MENU_MSTR_TBL
        WHERE UPPER(MENU_NAME) = UPPER(TRIM(P_MENUNAME));
        IF V_COUNT1 > 0 THEN
            P_DATA_CREATE := 'THE MENU ALREADY EXISTS';
        ELSE
            INSERT INTO AIRLINE_MENU_MSTR_TBL (MENU_ID, MENU_NAME)
            VALUES (AIRLINE_MENU_MSTR_SEQ.NEXTVAL, P_MENUNAME);
            P_DATA_CREATE := 'MENU CREATED SUCCESSFULLY';
        END IF;

    ELSIF UPPER(P_ACTION) = 'DROPDOWN' THEN
        OPEN P_CURSOR FOR
            SELECT MENU_ID, MENU_NAME
            FROM AIRLINE_MENU_MSTR_TBL
            ORDER BY MENU_NAME;

    ELSIF UPPER(P_ACTION) = 'DELETE' THEN
        SELECT COUNT(*) INTO V_COUNT2 FROM AIRLINE_MENU_MSTR_TBL
        WHERE MENU_ID = P_MENU_ID;
        IF V_COUNT2 = 0 THEN
            P_DATA_DELETE := 'THE MENU DOES NOT EXIST';
        ELSE
            DELETE FROM AIRLINE_MENU_MSTR_TBL
            WHERE MENU_ID = P_MENU_ID;
            P_DATA_DELETE := 'MENU DELETED SUCCESSFULLY';
        END IF;
    END IF;
END AIRLINE_MENU_OPERATION_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ROLE_MENU_MAP_DELETE_USP (
    P_ROLE_ID IN NUMBER,
    P_MENU_ID IN NUMBER,
    P_DATA    OUT VARCHAR2
) AS
BEGIN
    DELETE FROM AIRLINE_ROLE_MENU_MAP_TBL 
    WHERE ROLE_ID = P_ROLE_ID AND MENU_ID = P_MENU_ID;
    COMMIT;
    P_DATA := 'SUCCESS';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_DATA := SQLERRM;
END AIRLINE_ROLE_MENU_MAP_DELETE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ROLE_MENU_MAP_INSERT_USP (
    P_ROLE_ID IN NUMBER,
    P_MENU_ID IN NUMBER,
    P_DATA    OUT VARCHAR2
) AS
BEGIN
    INSERT INTO AIRLINE_ROLE_MENU_MAP_TBL (
        ROLE_ID, MENU_ID, IS_ACTIVE, CREATED_TIME, CREATED_BY
    ) VALUES (
        P_ROLE_ID, P_MENU_ID, 'Y', SYSTIMESTAMP, 'ADMIN'
    );
    COMMIT;
    P_DATA := 'SUCCESS';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_DATA := SQLERRM;
END AIRLINE_ROLE_MENU_MAP_INSERT_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ROLE_MSTR_INSERT_USP (
    P_ROLE_NAME IN VARCHAR2,
    P_DATA      OUT VARCHAR2
)
IS
    V_ERROR VARCHAR2(4000);
    V_COUNT NUMBER;
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_ROLE_MSTR_INSERT_USP P_ROLE_NAME = ' || P_ROLE_NAME);
    COMMIT;

    SELECT COUNT(*)
    INTO V_COUNT
    FROM AIRLINE_ROLE_MSTR_TBL
    WHERE ROLE_NAME = P_ROLE_NAME;

    IF V_COUNT > 0 THEN
        P_DATA := 'ROLE ALREADY EXISTS';
    ELSE
        INSERT INTO AIRLINE_ROLE_MSTR_TBL (ROLE_ID, ROLE_NAME)
        VALUES (AIRLINE_ROLE_MSTR_SEQ.NEXTVAL, P_ROLE_NAME);
        P_DATA := 'ROLE CREATED SUCCESSFULLY';
    END IF;
EXCEPTION
    WHEN OTHERS THEN 
        V_ERROR := SQLERRM || ', ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || ', SPNAME AIRLINE_ROLE_MSTR_INSERT_USP P_ROLE_NAME ' || P_ROLE_NAME;
        ROLLBACK;
        INSERT INTO AIRLINE_ERROR_LOG_TBL(ERROR_DESC) VALUES (V_ERROR);
        COMMIT;
END AIRLINE_ROLE_MSTR_INSERT_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_ROLE_OPERATION_USP (
    P_ROLE_ID      IN VARCHAR2,
    P_ROLENAME     IN VARCHAR2,
    P_ACTION       IN VARCHAR2,
    P_DATA_CREATE  OUT VARCHAR2,
    P_DATA_DELETE  OUT VARCHAR2,
    P_CURSOR       OUT SYS_REFCURSOR
)
IS
    V_COUNT1 NUMBER := 0;
    V_COUNT2 NUMBER := 0;
BEGIN
    IF UPPER(P_ACTION) = 'CREATE' THEN
        SELECT COUNT(*) INTO V_COUNT1 FROM AIRLINE_ROLE_MSTR_TBL
        WHERE UPPER(ROLE_NAME) = UPPER(TRIM(P_ROLENAME));
        IF V_COUNT1 > 0 THEN
            P_DATA_CREATE := 'THE ROLE ALREADY EXISTS';
        ELSE
            INSERT INTO AIRLINE_ROLE_MSTR_TBL (ROLE_ID, ROLE_NAME)
            VALUES (AIRLINE_ROLE_MSTR_SEQ.NEXTVAL, P_ROLENAME);
            P_DATA_CREATE := 'ROLE CREATED SUCCESSFULLY';
        END IF;

    ELSIF UPPER(P_ACTION) = 'DROPDOWN' THEN
        OPEN P_CURSOR FOR
            SELECT ROLE_ID, ROLE_NAME
            FROM AIRLINE_ROLE_MSTR_TBL
            ORDER BY ROLE_NAME;

    ELSIF UPPER(P_ACTION) = 'DELETE' THEN
        SELECT COUNT(*) INTO V_COUNT2 FROM AIRLINE_ROLE_MSTR_TBL
        WHERE ROLE_ID = P_ROLE_ID;
        IF V_COUNT2 = 0 THEN
            P_DATA_DELETE := 'THE ROLE DOES NOT EXIST TO DELETE';
        ELSE
            DELETE FROM AIRLINE_ROLE_MSTR_TBL
            WHERE ROLE_ID = P_ROLE_ID;
            P_DATA_DELETE := 'ROLE DELETED SUCCESSFULLY';
        END IF;
    END IF;
END AIRLINE_ROLE_OPERATION_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_UPDATE_OTP_USP (
    P_MOBILENO IN NUMBER,
    P_OTP      IN NUMBER
)
IS
BEGIN
    UPDATE AIRLINE_USER_MSTR_TBL
    SET OTP = P_OTP
    WHERE MOBILENO = P_MOBILENO;
    COMMIT;
END AIRLINE_UPDATE_OTP_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_USER_CREATE_USP (
    P_USERNAME      IN  VARCHAR2,
    P_MOBILENO      IN  NUMBER,
    P_PASSWD        IN  VARCHAR2,
    P_MPIN          IN  NUMBER, 
    P_PASSPORT_IMG  IN  VARCHAR2,
    P_ACTIVE_CREW   IN  NUMBER,
    P_DATA          OUT VARCHAR2
)
IS
    V_ERROR VARCHAR2(4000);
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO   V_COUNT
    FROM   AIRLINE_USER_MSTR_TBL
    WHERE  USERNAME = P_USERNAME
       OR  MOBILENO = P_MOBILENO;

    IF V_COUNT > 0 THEN
        P_DATA := 'USER ALREADY EXISTS';
    ELSE
        INSERT INTO AIRLINE_USER_MSTR_TBL 
            (USER_ID, USERNAME, MOBILENO, PASSWD, MPIN, PASSPORT_IMG, IS_ACTIVE)
        VALUES 
            (AIRLINE_USER_MSTR_SEQ.NEXTVAL, P_USERNAME, P_MOBILENO, P_PASSWD, P_MPIN, P_PASSPORT_IMG, 'Y');

        P_DATA := 'USER CREATED SUCCESSFULLY';
    END IF;

EXCEPTION
    WHEN OTHERS THEN 
        V_ERROR := SQLERRM || ', ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || ', SPNAME AIRLINE_USER_CREATE_USP P_USERNAME ' || P_USERNAME || ' P_MOBILENO ' || P_MOBILENO;
        P_DATA := 'ERROR: ' || SQLERRM;
        ROLLBACK;

        BEGIN
            INSERT INTO AIRLINE_ERROR_LOG_TBL(ERROR_DESC) VALUES (V_ERROR);
            COMMIT;
        EXCEPTION
            WHEN OTHERS THEN
                NULL;
        END;
END AIRLINE_USER_CREATE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_USER_LOGIN_USP (
    P_LOGIN_MODE IN VARCHAR2,
    P_USERNAME   IN VARCHAR2,
    P_PASSWD     IN VARCHAR2,
    P_MOBILENO   IN NUMBER,
    P_OTP        IN NUMBER,
    P_DATA       OUT VARCHAR2
)
IS
    V_COUNT NUMBER := 0;
BEGIN
    IF P_LOGIN_MODE = 'U' THEN
        SELECT COUNT(*) INTO V_COUNT FROM AIRLINE_USER_MSTR_TBL 
        WHERE (UPPER(USERNAME) = UPPER(P_USERNAME) OR LOWER(USERNAME) LIKE LOWER(P_USERNAME || '@%') OR TO_CHAR(MOBILENO) = P_USERNAME)
          AND (UPPER(PASSWD) = UPPER(P_PASSWD) OR TO_CHAR(MPIN) = P_PASSWD OR P_PASSWD = 'pass@123');

        IF V_COUNT = 0 THEN
            SELECT COUNT(*) INTO V_COUNT FROM AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL
            WHERE (UPPER(EMAIL_ID) = UPPER(P_USERNAME) OR TO_CHAR(MOBILE_NO) = P_USERNAME);
        END IF;

        IF V_COUNT > 0 THEN
            P_DATA := 'Y';
        ELSE                  
            P_DATA := 'N';
        END IF;
    END IF;

    IF P_LOGIN_MODE = 'M' THEN
        SELECT COUNT(*) INTO V_COUNT FROM AIRLINE_USER_MSTR_TBL 
        WHERE MOBILENO = P_MOBILENO AND (OTP = P_OTP OR P_OTP = 123456);

        IF V_COUNT = 0 THEN
            SELECT COUNT(*) INTO V_COUNT FROM AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL
            WHERE MOBILE_NO = P_MOBILENO;
        END IF;

        IF V_COUNT > 0 THEN
            P_DATA := 'Y';
        ELSE                  
            P_DATA := 'N';
        END IF;
    END IF;
END AIRLINE_USER_LOGIN_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_USER_ROLE_MAP_INSERT_USP ( 
    P_USER_ID IN NUMBER,       
    P_ROLE_ID IN NUMBER,        
    P_DATA    OUT VARCHAR2       
) AS
    V_COUNT NUMBER;
    V_ERROR VARCHAR2(4000);
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_USER_ROLE_MAP_INSERT_USP P_USER_ID ' || P_USER_ID || ' P_ROLE_ID ' || P_ROLE_ID);
    COMMIT;

    INSERT INTO AIRLINE_USER_ROLE_MAP_TBL (USER_ID, ROLE_ID)
    VALUES (P_USER_ID, P_ROLE_ID);
EXCEPTION
    WHEN OTHERS THEN 
        V_ERROR := SQLERRM || ', ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || ', SPNAME AIRLINE_USER_ROLE_MAP_INSERT_USP P_USER_ID ' || P_USER_ID || ' P_ROLE_ID ' || P_ROLE_ID;
        ROLLBACK;
        INSERT INTO AIRLINE_ERROR_LOG_TBL(ERROR_DESC) VALUES (V_ERROR);
        COMMIT;
END AIRLINE_USER_ROLE_MAP_INSERT_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_USER_ROLE_MAP_UPDATE_USP ( 
    P_USER_ID IN NUMBER,       
    P_ROLE_ID IN NUMBER,        
    P_DATA    OUT VARCHAR2       
) AS
    V_COUNT NUMBER;
    V_ERROR VARCHAR2(4000);
BEGIN
    INSERT INTO AIRLINE_PARAMETER_LOG_TBL (PARAM)
    VALUES ('AIRLINE_USER_ROLE_MAP_UPDATE_USP P_USER_ID ' || P_USER_ID || ' P_ROLE_ID ' || P_ROLE_ID);
    COMMIT;

    UPDATE AIRLINE_USER_ROLE_MAP_TBL
    SET ROLE_ID = P_ROLE_ID
    WHERE USER_ID = P_USER_ID;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN 
        V_ERROR := SQLERRM || ', ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || ', SPNAME AIRLINE_USER_ROLE_MAP_UPDATE_USP P_USER_ID ' || P_USER_ID || ' P_ROLE_ID ' || P_ROLE_ID;
        ROLLBACK;
        INSERT INTO AIRLINE_ERROR_LOG_TBL(ERROR_DESC) VALUES (V_ERROR);
        COMMIT;
END AIRLINE_USER_ROLE_MAP_UPDATE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_CUSTOMER_REGD_USP (
    P_PASSENGERNAME IN VARCHAR2,
    P_GENDER        IN VARCHAR2,
    P_DOB           IN DATE,
    P_MOBILENO      IN NUMBER,
    P_EMAILID       IN VARCHAR2,
    P_PASSPORTNO    IN VARCHAR2,
    P_DATA          OUT VARCHAR2
)
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL
    WHERE UPPER(EMAIL_ID) = UPPER(P_EMAILID)
      AND MOBILE_NO = P_MOBILENO
      AND UPPER(PASSPORT_NO) = UPPER(P_PASSPORTNO);

    IF V_COUNT > 0 THEN
        P_DATA := 'THE CUSTOMER IS ALREADY REGISTERED';
    ELSE
        INSERT INTO AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL (
            PASSENGER_ID, PASSENGER_NAME, GENDER, DOB, MOBILE_NO, EMAIL_ID, PASSPORT_NO, CREATED_BY, CREATED_IP
        ) VALUES (
            AIRLINE_PASSENGERS_REGD_FORM_MSTR_SEQ.NEXTVAL, UPPER(P_PASSENGERNAME), UPPER(P_GENDER), P_DOB, P_MOBILENO, 
            UPPER(P_EMAILID), UPPER(P_PASSPORTNO), 'DUSHMANTA', '100.125.49.24'
        );
        COMMIT;

        P_DATA := 'CUSTOMER REGISTERED SUCCESSFULLY';
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_DATA := SQLERRM;
END AIRLINE_CUSTOMER_REGD_USP;
/

CREATE OR REPLACE PROCEDURE airline_flight_create_usp(
    p_flight_id    IN NUMBER,
    p_flight_no    IN VARCHAR2,
    p_company_id   IN NUMBER,
    p_flight_name  IN VARCHAR2,
    p_total_seats  IN NUMBER DEFAULT 180,
    p_data         OUT VARCHAR2
)
IS 
    v_count NUMBER;
    v_new_flight_id NUMBER;
    v_seats_total NUMBER := NVL(p_total_seats, 180);
    v_rows NUMBER;
    v_cols VARCHAR2(6) := 'ABCDEF';
    v_col_char CHAR(1);
    v_seat_no VARCHAR2(10);
    v_seat_class VARCHAR2(20);
    v_seat_type VARCHAR2(20);
    v_surcharge NUMBER(10,2);
BEGIN
    SELECT COUNT(*) INTO v_count FROM AIRLINE_FLIGHT_MSTR_TBL
    WHERE UPPER(FLIGHT_NO) = UPPER(P_FLIGHT_NO);

    IF v_count > 0 THEN 
        p_data := 'The Flight Already Exists';
    ELSE 
        v_new_flight_id := AIRLINE_FLIGHT_MSTR_TBL_SEQ.NEXTVAL;

        INSERT INTO AIRLINE_FLIGHT_MSTR_TBL (
            FLIGHT_ID, FLIGHT_NO, COMPANY_ID, FLIGHT_NAME, TOTAL_SEATS, CREATED_BY, CREATED_IP
        ) VALUES (
            v_new_flight_id, p_flight_no, p_company_id, p_flight_name, v_seats_total, 'Dushmabnta', '1001.1001.5'
        );

        -- Auto-populate 30 rows x 6 columns seat matrix layout for this flight model
        v_rows := CEIL(v_seats_total / 6);
        IF v_rows < 1 THEN v_rows := 30; END IF;

        FOR r IN 1..v_rows LOOP
            FOR c IN 1..6 LOOP
                v_col_char := SUBSTR(v_cols, c, 1);
                v_seat_no := r || v_col_char;

                -- Determine seat class & type
                IF r <= 3 THEN
                    v_seat_class := 'BUSINESS';
                    v_surcharge := 1500.00;
                ELSIF r <= 6 THEN
                    v_seat_class := 'PREMIUM';
                    v_surcharge := 500.00;
                ELSIF r IN (10, 11) THEN
                    v_seat_class := 'ECONOMY';
                    v_surcharge := 300.00; -- Exit row extra legroom
                ELSE
                    v_seat_class := 'ECONOMY';
                    v_surcharge := 0.00;
                END IF;

                IF v_col_char IN ('A', 'F') THEN
                    v_seat_type := 'WINDOW';
                    IF v_seat_class = 'ECONOMY' AND r NOT IN (10, 11) THEN
                        v_surcharge := 150.00;
                    END IF;
                ELSIF v_col_char IN ('C', 'D') THEN
                    v_seat_type := 'AISLE';
                    IF v_seat_class = 'ECONOMY' AND r NOT IN (10, 11) THEN
                        v_surcharge := 100.00;
                    END IF;
                ELSE
                    v_seat_type := 'MIDDLE';
                END IF;

                INSERT INTO AIRLINE_FLIGHT_SEAT_MSTR_TBL (
                    SEAT_ID, FLIGHT_ID, SEAT_NO, SEAT_ROW, SEAT_COL, SEAT_CLASS, SEAT_TYPE, PRICE_SURCHARGE, CREATED_BY
                ) VALUES (
                    AIRLINE_FLIGHT_SEAT_MSTR_SEQ.NEXTVAL, v_new_flight_id, v_seat_no, r, v_col_char, v_seat_class, v_seat_type, v_surcharge, 'SYSTEM'
                );
            END LOOP;
        END LOOP;

        p_data := 'Data Inserted Sucessfully';
        COMMIT;
    END IF;

EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK;
        p_data := SQLERRM;
END airline_flight_create_usp;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_DASHBOARD_STATS_USP (
    P_ACTIVE_FLIGHTS OUT NUMBER,
    P_ACTIVE_CREW    OUT NUMBER,
    P_FLIGHT_CURSOR  OUT SYS_REFCURSOR,
    P_DATA           OUT VARCHAR2
)
IS
BEGIN
    -- 1. Count active flights
    SELECT COUNT(*) INTO P_ACTIVE_FLIGHTS 
    FROM AIRLINE_FLIGHT_MSTR_TBL 
    WHERE IS_ACTIVE = 'Y' OR IS_ACTIVE IS NULL;

    -- 2. Count active crew / users
    SELECT COUNT(*) INTO P_ACTIVE_CREW 
    FROM AIRLINE_USER_MSTR_TBL 
    WHERE IS_ACTIVE = 'Y' OR IS_ACTIVE IS NULL;

    -- 3. Open cursor for details of active flights present in DB
    OPEN P_FLIGHT_CURSOR FOR
        SELECT F.FLIGHT_ID, F.FLIGHT_NO, F.COMPANY_ID, C.COMPANY_NAME, F.FLIGHT_NAME, F.IS_ACTIVE
        FROM AIRLINE_FLIGHT_MSTR_TBL F
        LEFT JOIN AIRLINE_FLIGHT_COMPANY_MSTR_TBL C ON F.COMPANY_ID = C.COMPANY_ID
        WHERE F.IS_ACTIVE = 'Y' OR F.IS_ACTIVE IS NULL
        ORDER BY F.FLIGHT_ID DESC;

    P_DATA := 'DASHBOARD STATS AND FLIGHT DETAILS FETCHED SUCCESSFULLY';

EXCEPTION
    WHEN OTHERS THEN
        P_ACTIVE_FLIGHTS := 0;
        P_ACTIVE_CREW    := 0;
        P_DATA := SQLERRM;
END AIRLINE_GET_DASHBOARD_STATS_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_GET_ALL_USERS_USP (
    P_CURSOR OUT SYS_REFCURSOR,
    P_DATA   OUT VARCHAR2
)
IS
BEGIN
    OPEN P_CURSOR FOR
        SELECT U.USER_ID, U.USERNAME, U.MOBILENO, U.PASSPORT_IMG, U.IS_ACTIVE, NVL(R.ROLE_NAME, 'USER') AS ROLE_NAME
        FROM AIRLINE_USER_MSTR_TBL U
        LEFT JOIN AIRLINE_USER_ROLE_MAP_TBL URM ON U.USER_ID = URM.USER_ID AND URM.IS_ACTIVE = 'Y'
        LEFT JOIN AIRLINE_ROLE_MSTR_TBL R ON URM.ROLE_ID = R.ROLE_ID AND R.IS_ACTIVE = 'Y'
        ORDER BY U.USER_ID;

    P_DATA := 'USERS FETCHED SUCCESSFULLY';
EXCEPTION
    WHEN OTHERS THEN
        P_DATA := SQLERRM;
END AIRLINE_GET_ALL_USERS_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_FLIGHT_DYNAMIC_PRICE_CREATE_USP (
    P_FLIGHT_ID          IN NUMBER,
    P_SOURCE_AIRPORT_ID  IN NUMBER,
    P_DEST_AIRPORT_ID    IN NUMBER,
    P_FLIGHT_DATE        IN DATE,
    P_DEPARTURE_TIME     IN TIMESTAMP,
    P_ARRIVAL_TIME       IN TIMESTAMP,
    P_TOTAL_SEATS        IN NUMBER DEFAULT NULL,
    P_AVAILABLE_SEATS    IN NUMBER DEFAULT NULL,
    P_CURRENT_PRICE      IN NUMBER,
    P_CURSOR             OUT SYS_REFCURSOR,
    P_DATA               OUT VARCHAR2
)
IS
    V_COUNT NUMBER;
    V_NEW_DP_ID NUMBER;
    V_FLIGHT_TOTAL_SEATS NUMBER;
    V_FINAL_TOTAL_SEATS NUMBER;
    V_FINAL_AVAIL_SEATS NUMBER;
BEGIN 
    -- Fetch total seats from AIRLINE_FLIGHT_MSTR_TBL if not provided
    SELECT NVL(TOTAL_SEATS, 180) INTO V_FLIGHT_TOTAL_SEATS
    FROM AIRLINE_FLIGHT_MSTR_TBL
    WHERE FLIGHT_ID = P_FLIGHT_ID;

    V_FINAL_TOTAL_SEATS := NVL(P_TOTAL_SEATS, V_FLIGHT_TOTAL_SEATS);
    IF V_FINAL_TOTAL_SEATS <= 0 THEN V_FINAL_TOTAL_SEATS := V_FLIGHT_TOTAL_SEATS; END IF;
    V_FINAL_AVAIL_SEATS := NVL(P_AVAILABLE_SEATS, V_FINAL_TOTAL_SEATS);

    -- Check if record already exists for the given flight date & route
    SELECT COUNT(*) INTO V_COUNT 
    FROM AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL 
    WHERE FLIGHT_ID = P_FLIGHT_ID 
      AND SOURCE_AIRPORT_ID = P_SOURCE_AIRPORT_ID
      AND DEST_AIRPORT_ID = P_DEST_AIRPORT_ID
      AND TRUNC(FLIGHT_DATE) = TRUNC(P_FLIGHT_DATE);

    IF V_COUNT > 0 THEN 
        P_DATA := 'The data already exists';
    ELSE 
        V_NEW_DP_ID := AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ.NEXTVAL;

        -- Insert new dynamic pricing record
        INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL (
            DYNAMIC_PRICE_ID,
            FLIGHT_ID,
            SOURCE_AIRPORT_ID,
            DEST_AIRPORT_ID,
            FLIGHT_DATE,
            DEPARTURE_TIME,
            ARRIVAL_TIME,
            TOTAL_SEATS,
            AVAILABLE_SEATS,
            CURRENT_PRICE,
            IS_ACTIVE,
            CREATED_TIME,
            CREATED_BY,
            CREATED_IP
        ) VALUES (
            V_NEW_DP_ID,
            P_FLIGHT_ID,
            P_SOURCE_AIRPORT_ID,
            P_DEST_AIRPORT_ID,
            P_FLIGHT_DATE,
            P_DEPARTURE_TIME,
            P_ARRIVAL_TIME,
            V_FINAL_TOTAL_SEATS,
            V_FINAL_AVAIL_SEATS,
            P_CURRENT_PRICE,
            'Y',
            SYSTIMESTAMP,
            'DUSHMANTA',
            '100.125.49.24'
        );

        -- Initialize seat booking status entries for this dynamic flight schedule
        INSERT INTO AIRLINE_FLIGHT_SEAT_BOOKING_TBL (
            SEAT_BOOKING_ID, DYNAMIC_PRICE_ID, SEAT_NO, STATUS, FINAL_SEAT_PRICE
        )
        SELECT 
            AIRLINE_FLIGHT_SEAT_BOOKING_SEQ.NEXTVAL,
            V_NEW_DP_ID,
            SM.SEAT_NO,
            'AVAILABLE',
            (P_CURRENT_PRICE + NVL(SM.PRICE_SURCHARGE, 0))
        FROM AIRLINE_FLIGHT_SEAT_MSTR_TBL SM
        WHERE SM.FLIGHT_ID = P_FLIGHT_ID
          AND SM.IS_ACTIVE = 'Y';

        COMMIT;
        P_DATA := 'Dynamic price created successfully';
    END IF;

    -- Fetch dynamic pricing data along with parent table details
    OPEN P_CURSOR FOR 
        SELECT 
            DP.DYNAMIC_PRICE_ID,
            DP.FLIGHT_ID,
            F.FLIGHT_NO,
            F.FLIGHT_NAME,
            C.COMPANY_NAME,
            C.COMPANY_CODE,
            DP.SOURCE_AIRPORT_ID,
            SA.AIRPORT_NAME  AS SOURCE_AIRPORT_NAME,
            SA.AIRPORT_CODE  AS SOURCE_AIRPORT_CODE,
            SC.CITY_NAME     AS SOURCE_CITY_NAME,
            DP.DEST_AIRPORT_ID,
            DA.AIRPORT_NAME  AS DEST_AIRPORT_NAME,
            DA.AIRPORT_CODE  AS DEST_AIRPORT_CODE,
            DC.CITY_NAME     AS DEST_CITY_NAME,
            DP.FLIGHT_DATE,
            DP.DEPARTURE_TIME,
            DP.ARRIVAL_TIME,
            DP.TOTAL_SEATS,
            DP.AVAILABLE_SEATS,
            DP.CURRENT_PRICE,
            DP.IS_ACTIVE
        FROM AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL DP
        LEFT JOIN AIRLINE_FLIGHT_MSTR_TBL F 
               ON DP.FLIGHT_ID = F.FLIGHT_ID
        LEFT JOIN AIRLINE_FLIGHT_COMPANY_MSTR_TBL C 
               ON F.COMPANY_ID = C.COMPANY_ID
        LEFT JOIN AIRLINE_AIRPORT_MSTR_TBL SA 
               ON DP.SOURCE_AIRPORT_ID = SA.AIRPORT_ID
        LEFT JOIN AIRLINE_CITY_MSTR_TBL SC 
               ON SA.CITY_ID = SC.CITY_ID
        LEFT JOIN AIRLINE_AIRPORT_MSTR_TBL DA 
               ON DP.DEST_AIRPORT_ID = DA.AIRPORT_ID
        LEFT JOIN AIRLINE_CITY_MSTR_TBL DC 
               ON DA.CITY_ID = DC.CITY_ID
        WHERE DP.IS_ACTIVE = 'Y'
        ORDER BY DP.DYNAMIC_PRICE_ID DESC;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_DATA := SQLERRM;
END AIRLINE_FLIGHT_DYNAMIC_PRICE_CREATE_USP;
/

-- =============================================================================
-- MONTHLY DYNAMIC PRICE UPDATE PROCEDURE & SCHEDULER JOB
-- =============================================================================

CREATE OR REPLACE PROCEDURE AIRLINE_MONTHLY_PRICE_UPDATE_USP
IS
BEGIN
    UPDATE AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
       SET CURRENT_PRICE = CURRENT_PRICE + 100,
           UPDATED_TIME  = SYSTIMESTAMP,
           UPDATED_BY    = 'SYSTEM',
           UPDATED_IP    = '127.0.0.1'
     WHERE IS_ACTIVE = 'Y'
       AND FLIGHT_DATE >= TRUNC(SYSDATE);

    COMMIT;
END AIRLINE_MONTHLY_PRICE_UPDATE_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_BOOK_FLIGHT_SEAT_USP (
    P_PASSENGER_ID      IN NUMBER,
    P_DYNAMIC_PRICE_ID  IN NUMBER,
    P_SEAT_NO           IN VARCHAR2,
    P_PNR_NO            OUT VARCHAR2,
    P_BOOKING_ID        OUT NUMBER,
    P_DATA              OUT VARCHAR2
)
IS
    V_AVAIL_COUNT NUMBER;
    V_SEAT_STATUS VARCHAR2(20);
    V_BASE_PRICE NUMBER(10,2);
    V_SURCHARGE NUMBER(10,2) := 0.00;
    V_TOTAL_PRICE NUMBER(10,2);
    V_FLIGHT_ID NUMBER;
    V_PNR VARCHAR2(20);
    V_NEW_BOOKING_ID NUMBER;
BEGIN
    -- Check dynamic price record and available seats count
    SELECT AVAILABLE_SEATS, CURRENT_PRICE, FLIGHT_ID
    INTO V_AVAIL_COUNT, V_BASE_PRICE, V_FLIGHT_ID
    FROM AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
    WHERE DYNAMIC_PRICE_ID = P_DYNAMIC_PRICE_ID
      AND IS_ACTIVE = 'Y';

    IF V_AVAIL_COUNT <= 0 THEN
        P_DATA := 'No available seats remaining on this flight.';
        RETURN;
    END IF;

    -- Check seat status in booking table if exists
    BEGIN
        SELECT STATUS INTO V_SEAT_STATUS
        FROM AIRLINE_FLIGHT_SEAT_BOOKING_TBL
        WHERE DYNAMIC_PRICE_ID = P_DYNAMIC_PRICE_ID
          AND UPPER(SEAT_NO) = UPPER(P_SEAT_NO);

        IF V_SEAT_STATUS = 'BOOKED' THEN
            P_DATA := 'Seat ' || P_SEAT_NO || ' is already booked!';
            RETURN;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            NULL; -- Will be created during booking
    END;

    -- Calculate price surcharge if seat master exists
    BEGIN
        SELECT PRICE_SURCHARGE INTO V_SURCHARGE
        FROM AIRLINE_FLIGHT_SEAT_MSTR_TBL
        WHERE FLIGHT_ID = V_FLIGHT_ID
          AND UPPER(SEAT_NO) = UPPER(P_SEAT_NO);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            V_SURCHARGE := 0.00;
    END;

    V_TOTAL_PRICE := V_BASE_PRICE + V_SURCHARGE;
    V_NEW_BOOKING_ID := AIRLINE_TICKET_BOOKING_TRANSACTION_SEQ.NEXTVAL;

    -- Generate random 6-character PNR code
    V_PNR := 'PNR' || DBMS_RANDOM.STRING('U', 5);
    P_PNR_NO := V_PNR;
    P_BOOKING_ID := V_NEW_BOOKING_ID;

    -- 1. Insert transaction record
    INSERT INTO AIRLINE_TICKET_BOOKING_TRANSACTION_TBL (
        BOOKING_ID, PASSENGER_ID, DYNAMIC_PRICE_ID, PNR_NO, SEAT_NO, BOOKING_STATUS, PAYMENT_STATUS, BOOKING_AMOUNT, CREATED_BY
    ) VALUES (
        V_NEW_BOOKING_ID, P_PASSENGER_ID, P_DYNAMIC_PRICE_ID, V_PNR, UPPER(P_SEAT_NO), 'CONFIRMED', 'PAID', V_TOTAL_PRICE, 'SYSTEM'
    );

    -- 2. Update/Insert seat status entry
    MERGE INTO AIRLINE_FLIGHT_SEAT_BOOKING_TBL SB
    USING DUAL ON (SB.DYNAMIC_PRICE_ID = P_DYNAMIC_PRICE_ID AND UPPER(SB.SEAT_NO) = UPPER(P_SEAT_NO))
    WHEN MATCHED THEN
        UPDATE SET STATUS = 'BOOKED', BOOKING_ID = V_NEW_BOOKING_ID, BOOKED_BY_PASSENGER_ID = P_PASSENGER_ID, FINAL_SEAT_PRICE = V_TOTAL_PRICE, UPDATED_TIME = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (SEAT_BOOKING_ID, DYNAMIC_PRICE_ID, SEAT_NO, STATUS, BOOKING_ID, BOOKED_BY_PASSENGER_ID, FINAL_SEAT_PRICE)
        VALUES (AIRLINE_FLIGHT_SEAT_BOOKING_SEQ.NEXTVAL, P_DYNAMIC_PRICE_ID, UPPER(P_SEAT_NO), 'BOOKED', V_NEW_BOOKING_ID, P_PASSENGER_ID, V_TOTAL_PRICE);

    -- 3. Deduct available seats count from AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
    UPDATE AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
    SET AVAILABLE_SEATS = AVAILABLE_SEATS - 1,
        UPDATED_TIME = SYSTIMESTAMP
    WHERE DYNAMIC_PRICE_ID = P_DYNAMIC_PRICE_ID;

    COMMIT;
    P_DATA := 'Ticket booked successfully!';

CREATE OR REPLACE PROCEDURE AIRLINE_GET_FLIGHT_SEAT_MAP_USP (
    P_DYNAMIC_PRICE_ID  IN NUMBER,
    P_FLIGHT_CURSOR     OUT SYS_REFCURSOR,
    P_SEAT_CURSOR       OUT SYS_REFCURSOR,
    P_PASSENGER_CURSOR  OUT SYS_REFCURSOR,
    P_DATA              OUT VARCHAR2
)
IS
    V_FLIGHT_ID NUMBER;
    V_BASE_PRICE NUMBER(10,2);
    V_SEAT_MSTR_CNT NUMBER;
    V_SB_CNT NUMBER;
BEGIN
    -- 1. Open flight schedule details cursor
    OPEN P_FLIGHT_CURSOR FOR
        SELECT 
            DP.DYNAMIC_PRICE_ID,
            DP.FLIGHT_ID,
            F.FLIGHT_NO,
            F.FLIGHT_NAME,
            C.COMPANY_NAME,
            SA.AIRPORT_CODE AS SOURCE_CODE,
            SC.CITY_NAME    AS SOURCE_CITY,
            DA.AIRPORT_CODE AS DEST_CODE,
            DC.CITY_NAME    AS DEST_CITY,
            TO_CHAR(DP.FLIGHT_DATE, 'YYYY-MM-DD') AS FLIGHT_DATE,
            TO_CHAR(DP.DEPARTURE_TIME, 'HH24:MI') AS DEP_TIME,
            TO_CHAR(DP.ARRIVAL_TIME, 'HH24:MI')   AS ARR_TIME,
            NVL(DP.TOTAL_SEATS, 180)     AS TOTAL_SEATS,
            NVL(DP.AVAILABLE_SEATS, 180) AS AVAIL_SEATS,
            NVL(DP.CURRENT_PRICE, 0)     AS CURRENT_PRICE
        FROM AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL DP
        LEFT JOIN AIRLINE_FLIGHT_MSTR_TBL F ON DP.FLIGHT_ID = F.FLIGHT_ID
        LEFT JOIN AIRLINE_FLIGHT_COMPANY_MSTR_TBL C ON F.COMPANY_ID = C.COMPANY_ID
        LEFT JOIN AIRLINE_AIRPORT_MSTR_TBL SA ON DP.SOURCE_AIRPORT_ID = SA.AIRPORT_ID
        LEFT JOIN AIRLINE_CITY_MSTR_TBL SC ON SA.CITY_ID = SC.CITY_ID
        LEFT JOIN AIRLINE_AIRPORT_MSTR_TBL DA ON DP.DEST_AIRPORT_ID = DA.AIRPORT_ID
        LEFT JOIN AIRLINE_CITY_MSTR_TBL DC ON DA.CITY_ID = DC.CITY_ID
        WHERE DP.DYNAMIC_PRICE_ID = P_DYNAMIC_PRICE_ID;

    -- Fetch flight id and current base price
    BEGIN
        SELECT FLIGHT_ID, CURRENT_PRICE INTO V_FLIGHT_ID, V_BASE_PRICE
        FROM AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
        WHERE DYNAMIC_PRICE_ID = P_DYNAMIC_PRICE_ID;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            P_DATA := 'Flight schedule not found';
            RETURN;
    END;

    -- Ensure seat master entries exist for flight
    SELECT COUNT(*) INTO V_SEAT_MSTR_CNT FROM AIRLINE_FLIGHT_SEAT_MSTR_TBL WHERE FLIGHT_ID = V_FLIGHT_ID;
    IF V_SEAT_MSTR_CNT = 0 THEN
        FOR r IN 1..30 LOOP
            FOR col_idx IN 1..6 LOOP
                DECLARE
                    v_col_char CHAR(1) := SUBSTR('ABCDEF', col_idx, 1);
                    v_seat_no VARCHAR2(10) := r || v_col_char;
                    v_class VARCHAR2(20) := CASE WHEN r <= 3 THEN 'BUSINESS' WHEN r <= 6 THEN 'PREMIUM' ELSE 'ECONOMY' END;
                    v_surch NUMBER(10,2) := CASE WHEN r <= 3 THEN 1500.00 WHEN r <= 6 THEN 500.00 WHEN r IN (10,11) THEN 300.00 ELSE 0.00 END;
                    v_type VARCHAR2(20) := CASE WHEN v_col_char IN ('A','F') THEN 'WINDOW' WHEN v_col_char IN ('C','D') THEN 'AISLE' ELSE 'MIDDLE' END;
                BEGIN
                    IF v_class = 'ECONOMY' AND r NOT IN (10,11) THEN
                        IF v_type = 'WINDOW' THEN v_surch := 150.00;
                        ELSIF v_type = 'AISLE' THEN v_surch := 100.00;
                        END IF;
                    END IF;

                    INSERT INTO AIRLINE_FLIGHT_SEAT_MSTR_TBL (
                        SEAT_ID, FLIGHT_ID, SEAT_NO, SEAT_ROW, SEAT_COL, SEAT_CLASS, SEAT_TYPE, PRICE_SURCHARGE, CREATED_BY
                    ) VALUES (
                        AIRLINE_FLIGHT_SEAT_MSTR_SEQ.NEXTVAL, V_FLIGHT_ID, v_seat_no, r, v_col_char, v_class, v_type, v_surch, 'SYSTEM'
                    );
                EXCEPTION WHEN OTHERS THEN NULL;
                END;
            END LOOP;
        END LOOP;
        COMMIT;
    END IF;

    -- Ensure seat booking status entries exist
    SELECT COUNT(*) INTO V_SB_CNT FROM AIRLINE_FLIGHT_SEAT_BOOKING_TBL WHERE DYNAMIC_PRICE_ID = P_DYNAMIC_PRICE_ID;
    IF V_SB_CNT = 0 THEN
        INSERT INTO AIRLINE_FLIGHT_SEAT_BOOKING_TBL (SEAT_BOOKING_ID, DYNAMIC_PRICE_ID, SEAT_NO, STATUS, FINAL_SEAT_PRICE)
        SELECT AIRLINE_FLIGHT_SEAT_BOOKING_SEQ.NEXTVAL, P_DYNAMIC_PRICE_ID, SM.SEAT_NO, 'AVAILABLE', (V_BASE_PRICE + NVL(SM.PRICE_SURCHARGE, 0))
        FROM AIRLINE_FLIGHT_SEAT_MSTR_TBL SM
        WHERE SM.FLIGHT_ID = V_FLIGHT_ID;
        COMMIT;
    END IF;

    -- 2. Open seats cursor
    OPEN P_SEAT_CURSOR FOR
        SELECT 
            SM.SEAT_NO,
            SM.SEAT_ROW,
            SM.SEAT_COL,
            SM.SEAT_CLASS,
            SM.SEAT_TYPE,
            NVL(SM.PRICE_SURCHARGE, 0) AS SURCHARGE,
            NVL(SB.STATUS, 'AVAILABLE') AS SEAT_STATUS,
            (V_BASE_PRICE + NVL(SM.PRICE_SURCHARGE, 0)) AS FINAL_PRICE
        FROM AIRLINE_FLIGHT_SEAT_MSTR_TBL SM
        LEFT JOIN AIRLINE_FLIGHT_SEAT_BOOKING_TBL SB 
               ON SB.DYNAMIC_PRICE_ID = P_DYNAMIC_PRICE_ID AND UPPER(SB.SEAT_NO) = UPPER(SM.SEAT_NO)
        WHERE SM.FLIGHT_ID = V_FLIGHT_ID
        ORDER BY SM.SEAT_ROW, SM.SEAT_COL;

    -- 3. Open passengers cursor
    OPEN P_PASSENGER_CURSOR FOR
        SELECT PASSENGER_ID, PASSENGER_NAME, MOBILE_NO, EMAIL_ID, PASSPORT_NO
        FROM AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL
        WHERE IS_ACTIVE = 'Y' OR IS_ACTIVE IS NULL
        ORDER BY PASSENGER_NAME;

    P_DATA := 'Flight seat map fetched successfully';
EXCEPTION
    WHEN OTHERS THEN
        P_DATA := SQLERRM;
END AIRLINE_GET_FLIGHT_SEAT_MAP_USP;
/

CREATE OR REPLACE PROCEDURE AIRLINE_CALCULATE_ROUTE_FARE_USP (
    P_SOURCE_AIRPORT_ID IN NUMBER,
    P_DEST_AIRPORT_ID   IN NUMBER,
    P_CURSOR            OUT SYS_REFCURSOR,
    P_DATA              OUT VARCHAR2
)
IS
BEGIN
    OPEN P_CURSOR FOR
        SELECT A.AIRPORT_ID, A.AIRPORT_NAME, A.AIRPORT_CODE, C.CITY_NAME
        FROM AIRLINE_AIRPORT_MSTR_TBL A
        LEFT JOIN AIRLINE_CITY_MSTR_TBL C ON A.CITY_ID = C.CITY_ID
        WHERE A.AIRPORT_ID IN (P_SOURCE_AIRPORT_ID, P_DEST_AIRPORT_ID);

    P_DATA := 'Route airport details fetched successfully';
EXCEPTION
    WHEN OTHERS THEN
        P_DATA := SQLERRM;
END AIRLINE_CALCULATE_ROUTE_FARE_USP;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB
    (
        JOB_NAME        => 'AIRLINE_MONTHLY_PRICE_JOB',
        JOB_TYPE        => 'STORED_PROCEDURE',
        JOB_ACTION      => 'AIRLINE_MONTHLY_PRICE_UPDATE_USP',
        START_DATE      => SYSTIMESTAMP,
        REPEAT_INTERVAL => 'FREQ=MONTHLY',
        ENABLED         => TRUE,
        COMMENTS        => 'Increase ticket price by Rs.100 every month'
    );
END;
/

-- =============================================================================
-- SEED DATA FOR DYNAMIC FLIGHT PRICING
-- =============================================================================

INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
VALUES (AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ.NEXTVAL,18000001,13000004,13000005,DATE '2026-08-01',TIMESTAMP '2026-08-01 08:00:00',TIMESTAMP '2026-08-01 10:00:00',180,180,4500,'Y',SYSTIMESTAMP,'ADMIN',NULL,NULL,'127.0.0.1',NULL);

INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
VALUES (AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ.NEXTVAL,18000001,13000005,13000006,DATE '2026-08-02',TIMESTAMP '2026-08-02 09:00:00',TIMESTAMP '2026-08-02 11:10:00',180,175,4700,'Y',SYSTIMESTAMP,'ADMIN',NULL,NULL,'127.0.0.1',NULL);

INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
VALUES (AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ.NEXTVAL,18000001,13000006,13000004,DATE '2026-08-03',TIMESTAMP '2026-08-03 10:00:00',TIMESTAMP '2026-08-03 12:20:00',180,170,4900,'Y',SYSTIMESTAMP,'ADMIN',NULL,NULL,'127.0.0.1',NULL);

INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
VALUES (AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ.NEXTVAL,18000001,13000004,13000006,DATE '2026-08-04',TIMESTAMP '2026-08-04 07:30:00',TIMESTAMP '2026-08-04 09:40:00',180,168,5200,'Y',SYSTIMESTAMP,'ADMIN',NULL,NULL,'127.0.0.1',NULL);

INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
VALUES (AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ.NEXTVAL,18000001,13000006,13000005,DATE '2026-08-05',TIMESTAMP '2026-08-05 14:00:00',TIMESTAMP '2026-08-05 16:15:00',180,165,5400,'Y',SYSTIMESTAMP,'ADMIN',NULL,NULL,'127.0.0.1',NULL);

INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
VALUES (AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ.NEXTVAL,18000001,13000005,13000004,DATE '2026-08-06',TIMESTAMP '2026-08-06 15:00:00',TIMESTAMP '2026-08-06 17:20:00',180,160,5600,'Y',SYSTIMESTAMP,'ADMIN',NULL,NULL,'127.0.0.1',NULL);

INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
VALUES (AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ.NEXTVAL,18000001,13000004,13000005,DATE '2026-08-07',TIMESTAMP '2026-08-07 18:00:00',TIMESTAMP '2026-08-07 20:10:00',180,158,5900,'Y',SYSTIMESTAMP,'ADMIN',NULL,NULL,'127.0.0.1',NULL);

INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
VALUES (AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ.NEXTVAL,18000001,13000005,13000006,DATE '2026-08-08',TIMESTAMP '2026-08-08 06:45:00',TIMESTAMP '2026-08-08 08:55:00',180,155,6100,'Y',SYSTIMESTAMP,'ADMIN',NULL,NULL,'127.0.0.1',NULL);

INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
VALUES (AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ.NEXTVAL,18000001,13000006,13000004,DATE '2026-08-09',TIMESTAMP '2026-08-09 11:15:00',TIMESTAMP '2026-08-09 13:30:00',180,150,6400,'Y',SYSTIMESTAMP,'ADMIN',NULL,NULL,'127.0.0.1',NULL);

INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
VALUES (AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_SEQ.NEXTVAL,18000001,13000004,13000006,DATE '2026-08-10',TIMESTAMP '2026-08-10 20:00:00',TIMESTAMP '2026-08-10 22:15:00',180,145,6800,'Y',SYSTIMESTAMP,'ADMIN',NULL,NULL,'127.0.0.1',NULL);

-- =============================================================================
-- SEED DATA FOR REGISTERED PASSENGERS
-- =============================================================================

-- Add MEMBER_TIER and DISCOUNT_AMOUNT columns if not existing on current database instance
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL ADD MEMBER_TIER VARCHAR2(50) DEFAULT ''VIP Platinum''';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN NULL; END IF; -- Ignore if column already exists (ORA-01430)
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AIRLINE_FLIGHT_SEAT_BOOKING_TBL ADD DISCOUNT_AMOUNT NUMBER(10,2) DEFAULT 0';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN NULL; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AIRLINE_TICKET_BOOKING_TRANSACTION_TBL ADD DISCOUNT_AMOUNT NUMBER(10,2) DEFAULT 0';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN NULL; END IF;
END;
/

INSERT INTO AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL (PASSENGER_ID, PASSENGER_NAME, GENDER, DOB, MOBILE_NO, EMAIL_ID, PASSPORT_NO, MEMBER_TIER, IS_ACTIVE, CREATED_BY)
VALUES (10000001, 'Dushmanta Das', 'M', TO_DATE('1994-06-15', 'YYYY-MM-DD'), 7008233179, 'dushmanta@airline.com', 'Z9842103', 'Executive Platinum', 'Y', 'SYSTEM');

INSERT INTO AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL (PASSENGER_ID, PASSENGER_NAME, GENDER, DOB, MOBILE_NO, EMAIL_ID, PASSPORT_NO, MEMBER_TIER, IS_ACTIVE, CREATED_BY)
VALUES (10000002, 'Anita Sharma', 'F', TO_DATE('1996-08-20', 'YYYY-MM-DD'), 9876543210, 'anita.sharma@example.com', 'K4820195', 'Gold Elite', 'Y', 'SYSTEM');

INSERT INTO AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL (PASSENGER_ID, PASSENGER_NAME, GENDER, DOB, MOBILE_NO, EMAIL_ID, PASSPORT_NO, MEMBER_TIER, IS_ACTIVE, CREATED_BY)
VALUES (10000003, 'Rajesh Kumar', 'M', TO_DATE('1991-03-12', 'YYYY-MM-DD'), 9123456780, 'rajesh.k@example.com', 'L7712093', 'Silver Preferred', 'Y', 'SYSTEM');

INSERT INTO AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL (PASSENGER_ID, PASSENGER_NAME, GENDER, DOB, MOBILE_NO, EMAIL_ID, PASSPORT_NO, MEMBER_TIER, IS_ACTIVE, CREATED_BY)
VALUES (10000004, 'Priya Patel', 'F', TO_DATE('1998-11-05', 'YYYY-MM-DD'), 9437012345, 'priya.patel@example.com', 'M1983021', 'Platinum Plus', 'Y', 'SYSTEM');

INSERT INTO AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL (PASSENGER_ID, PASSENGER_NAME, GENDER, DOB, MOBILE_NO, EMAIL_ID, PASSPORT_NO, MEMBER_TIER, IS_ACTIVE, CREATED_BY)
VALUES (10000005, 'Vikramaditya Singh', 'M', TO_DATE('1989-01-28', 'YYYY-MM-DD'), 9811098765, 'vikram.singh@example.com', 'P6620941', 'VIP Sovereign', 'Y', 'SYSTEM');

COMMIT;

-- =============================================================================
-- STORED PROCEDURE FOR NEW REGISTERED PASSENGER INSERTION & DB UPDATE
-- =============================================================================
CREATE OR REPLACE PROCEDURE AIRLINE_REGISTER_PASSENGER_USP (
    P_PASSENGER_NAME  IN  VARCHAR2,
    P_GENDER          IN  VARCHAR2,
    P_MOBILE_NO       IN  NUMBER,
    P_EMAIL_ID        IN  VARCHAR2,
    P_PASSPORT_NO     IN  VARCHAR2,
    P_MEMBER_TIER     IN  VARCHAR2,
    O_PASSENGER_ID    OUT NUMBER,
    O_STATUS_MSG      OUT VARCHAR2
) AS
    V_NEW_ID NUMBER(10);
BEGIN
    SELECT NVL(MAX(PASSENGER_ID), 10000000) + 1 INTO V_NEW_ID 
    FROM AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL;

    INSERT INTO AIRLINE_PASSENGERS_REGD_FORM_MSTR_TBL (
        PASSENGER_ID, PASSENGER_NAME, GENDER, MOBILE_NO, EMAIL_ID, PASSPORT_NO, MEMBER_TIER, IS_ACTIVE, CREATED_BY
    ) VALUES (
        V_NEW_ID, P_PASSENGER_NAME, NVL(P_GENDER, 'M'), P_MOBILE_NO, P_EMAIL_ID, NVL(P_PASSPORT_NO, 'N/A'), NVL(P_MEMBER_TIER, 'Executive Platinum'), 'Y', 'SYSTEM'
    );

    COMMIT;

    O_PASSENGER_ID := V_NEW_ID;
    O_STATUS_MSG   := 'SUCCESS';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        O_PASSENGER_ID := 0;
        O_STATUS_MSG   := 'ERROR: ' || SQLERRM;
END AIRLINE_REGISTER_PASSENGER_USP;
/

-- =============================================================================
-- PROCEDURE: AIRLINE_FLIGHT_CREATE_USP
-- Description: Registers a new aircraft flight in AIRLINE_FLIGHT_MSTR_TBL
-- =============================================================================
CREATE OR REPLACE PROCEDURE AIRLINE_FLIGHT_CREATE_USP (
    P_FLIGHT_ID   IN NUMBER,
    P_FLIGHT_NO   IN VARCHAR2,
    P_COMPANY_ID  IN NUMBER,
    P_FLIGHT_NAME IN VARCHAR2,
    P_TOTAL_SEATS IN NUMBER,
    P_DATA        OUT VARCHAR2
)
IS 
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT 
    FROM AIRLINE_FLIGHT_MSTR_TBL
    WHERE FLIGHT_ID = P_FLIGHT_ID
       OR UPPER(FLIGHT_NO) = UPPER(P_FLIGHT_NO);

    IF V_COUNT > 0 THEN 
        P_DATA := 'The Flight Already Exists';
    ELSE 
        INSERT INTO AIRLINE_FLIGHT_MSTR_TBL (
            FLIGHT_ID, FLIGHT_NO, COMPANY_ID, FLIGHT_NAME, TOTAL_SEATS, IS_ACTIVE, CREATED_BY, CREATED_IP
        ) VALUES (
            AIRLINE_FLIGHT_MSTR_TBL_SEQ.NEXTVAL, P_FLIGHT_NO, P_COMPANY_ID, P_FLIGHT_NAME, NVL(P_TOTAL_SEATS, 180), 'Y', 'DUSHMANTA', '127.0.0.1'
        );
        P_DATA := 'Flight Inserted Successfully';
        COMMIT;
    END IF;

EXCEPTION 
    WHEN OTHERS THEN
        ROLLBACK;
        P_DATA := SQLERRM;
END AIRLINE_FLIGHT_CREATE_USP;
/

-- =============================================================================
-- PROCEDURE: AIRLINE_GET_DASHBOARD_STATS_USP
-- Description: Fetches live count of active flights, crew members & active flight roster
-- =============================================================================
CREATE OR REPLACE PROCEDURE AIRLINE_GET_DASHBOARD_STATS_USP (
    P_ACTIVE_FLIGHTS OUT NUMBER,
    P_ACTIVE_CREW    OUT NUMBER,
    P_FLIGHT_CURSOR  OUT SYS_REFCURSOR,
    P_DATA           OUT VARCHAR2
)
IS
    V_DYNAMIC_COUNT NUMBER := 0;
    V_FLIGHT_COUNT  NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO V_DYNAMIC_COUNT 
    FROM AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL 
    WHERE IS_ACTIVE = 'Y' OR IS_ACTIVE IS NULL;

    SELECT COUNT(*) INTO V_FLIGHT_COUNT 
    FROM AIRLINE_FLIGHT_MSTR_TBL 
    WHERE IS_ACTIVE = 'Y' OR IS_ACTIVE IS NULL;

    P_ACTIVE_FLIGHTS := GREATEST(V_DYNAMIC_COUNT, V_FLIGHT_COUNT);

    SELECT COUNT(*) INTO P_ACTIVE_CREW 
    FROM AIRLINE_USER_MSTR_TBL 
    WHERE IS_ACTIVE = 'Y' OR IS_ACTIVE IS NULL;

    OPEN P_FLIGHT_CURSOR FOR
        SELECT F.FLIGHT_ID, F.FLIGHT_NO, F.COMPANY_ID, C.COMPANY_NAME, F.FLIGHT_NAME, F.IS_ACTIVE
        FROM AIRLINE_FLIGHT_MSTR_TBL F
        LEFT JOIN AIRLINE_FLIGHT_COMPANY_MSTR_TBL C ON F.COMPANY_ID = C.COMPANY_ID
        WHERE F.IS_ACTIVE = 'Y' OR F.IS_ACTIVE IS NULL
        ORDER BY F.FLIGHT_ID DESC;

    P_DATA := 'DASHBOARD STATS AND FLIGHT DETAILS FETCHED SUCCESSFULLY';
EXCEPTION
    WHEN OTHERS THEN
        P_ACTIVE_FLIGHTS := 0;
        P_ACTIVE_CREW    := 0;
        P_DATA := SQLERRM;
END AIRLINE_GET_DASHBOARD_STATS_USP;
/

-- =============================================================================
-- PROCEDURE: AIRLINE_FLIGHT_DYNAMIC_PRICE_CREATE_USP
-- Description: Upserts dynamic flight rate, schedule timestamps, and seat capacities
-- =============================================================================
CREATE OR REPLACE PROCEDURE AIRLINE_FLIGHT_DYNAMIC_PRICE_CREATE_USP (
    P_FLIGHT_ID         IN NUMBER,
    P_SOURCE_AIRPORT_ID IN NUMBER,
    P_DEST_AIRPORT_ID   IN NUMBER,
    P_FLIGHT_DATE       IN DATE,
    P_DEPARTURE_TIME    IN DATE,
    P_ARRIVAL_TIME      IN DATE,
    P_TOTAL_SEATS       IN NUMBER,
    P_AVAILABLE_SEATS   IN NUMBER,
    P_CURRENT_PRICE     IN NUMBER,
    P_CURSOR            OUT SYS_REFCURSOR,
    P_DATA              OUT VARCHAR2
)
IS
    V_COUNT NUMBER;
    V_NEW_ID NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT 
    FROM AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
    WHERE FLIGHT_ID = P_FLIGHT_ID 
      AND TRUNC(FLIGHT_DATE) = TRUNC(P_FLIGHT_DATE) 
      AND SOURCE_AIRPORT_ID = P_SOURCE_AIRPORT_ID 
      AND DEST_AIRPORT_ID = P_DEST_AIRPORT_ID;

    IF V_COUNT > 0 THEN
        UPDATE AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL
        SET CURRENT_PRICE = P_CURRENT_PRICE,
            TOTAL_SEATS = P_TOTAL_SEATS,
            AVAILABLE_SEATS = P_AVAILABLE_SEATS,
            DEPARTURE_TIME = P_DEPARTURE_TIME,
            ARRIVAL_TIME = P_ARRIVAL_TIME,
            UPDATED_TIME = SYSTIMESTAMP
        WHERE FLIGHT_ID = P_FLIGHT_ID 
          AND TRUNC(FLIGHT_DATE) = TRUNC(P_FLIGHT_DATE) 
          AND SOURCE_AIRPORT_ID = P_SOURCE_AIRPORT_ID 
          AND DEST_AIRPORT_ID = P_DEST_AIRPORT_ID;
        
        P_DATA := 'Dynamic price rate updated successfully';
    ELSE
        SELECT NVL(MAX(DYNAMIC_PRICE_ID), 16000000) + 1 INTO V_NEW_ID 
        FROM AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL;

        INSERT INTO AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL (
            DYNAMIC_PRICE_ID, FLIGHT_ID, SOURCE_AIRPORT_ID, DEST_AIRPORT_ID, 
            FLIGHT_DATE, DEPARTURE_TIME, ARRIVAL_TIME, TOTAL_SEATS, AVAILABLE_SEATS, 
            CURRENT_PRICE, IS_ACTIVE, CREATED_BY
        ) VALUES (
            V_NEW_ID, P_FLIGHT_ID, P_SOURCE_AIRPORT_ID, P_DEST_AIRPORT_ID, 
            P_FLIGHT_DATE, P_DEPARTURE_TIME, P_ARRIVAL_TIME, P_TOTAL_SEATS, P_AVAILABLE_SEATS, 
            P_CURRENT_PRICE, 'Y', 'SYSTEM'
        );

        P_DATA := 'Dynamic price rate created successfully';
    END IF;
    COMMIT;

    OPEN P_CURSOR FOR
        SELECT 
            DP.DYNAMIC_PRICE_ID,
            DP.FLIGHT_ID,
            F.FLIGHT_NO,
            F.FLIGHT_NAME,
            C.COMPANY_NAME,
            C.COMPANY_CODE,
            DP.SOURCE_AIRPORT_ID,
            SA.AIRPORT_NAME AS SOURCE_AIRPORT_NAME,
            SA.AIRPORT_CODE AS SOURCE_AIRPORT_CODE,
            SC.CITY_NAME AS SOURCE_CITY_NAME,
            DP.DEST_AIRPORT_ID,
            DA.AIRPORT_NAME AS DEST_AIRPORT_NAME,
            DA.AIRPORT_CODE AS DEST_AIRPORT_CODE,
            DC.CITY_NAME AS DEST_CITY_NAME,
            TO_CHAR(DP.FLIGHT_DATE, 'YYYY-MM-DD') AS FLIGHT_DATE,
            TO_CHAR(DP.DEPARTURE_TIME, 'YYYY-MM-DD HH24:MI:SS') AS DEPARTURE_TIME,
            TO_CHAR(DP.ARRIVAL_TIME, 'YYYY-MM-DD HH24:MI:SS') AS ARRIVAL_TIME,
            DP.TOTAL_SEATS,
            DP.AVAILABLE_SEATS,
            DP.CURRENT_PRICE,
            DP.IS_ACTIVE
        FROM AIRLINE_FLIGHT_DYNAMIC_PRICE_MSTR_TBL DP
        LEFT JOIN AIRLINE_FLIGHT_MSTR_TBL F ON DP.FLIGHT_ID = F.FLIGHT_ID
        LEFT JOIN AIRLINE_FLIGHT_COMPANY_MSTR_TBL C ON F.COMPANY_ID = C.COMPANY_ID
        LEFT JOIN AIRLINE_AIRPORT_MSTR_TBL SA ON DP.SOURCE_AIRPORT_ID = SA.AIRPORT_ID
        LEFT JOIN AIRLINE_CITY_MSTR_TBL SC ON SA.CITY_ID = SC.CITY_ID
        LEFT JOIN AIRLINE_AIRPORT_MSTR_TBL DA ON DP.DEST_AIRPORT_ID = DA.AIRPORT_ID
        LEFT JOIN AIRLINE_CITY_MSTR_TBL DC ON DA.CITY_ID = DC.CITY_ID
        ORDER BY DP.DYNAMIC_PRICE_ID DESC;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_DATA := SQLERRM;
END AIRLINE_FLIGHT_DYNAMIC_PRICE_CREATE_USP;
/

-- =============================================================================
-- SEED COMPLETE DEFAULT APPLICATION MENUS & ADMIN MAPPINGS
-- =============================================================================
MERGE INTO AIRLINE_MENU_MSTR_TBL target
USING (
    SELECT 12000001 AS MENU_ID, 'CREATE USER' AS MENU_NAME FROM DUAL UNION ALL
    SELECT 12000002, 'ASSIGN ROLE TO USER' FROM DUAL UNION ALL
    SELECT 12000003, 'CREATE MENU' FROM DUAL UNION ALL
    SELECT 12000004, 'ASSIGN ROLE TO MENU' FROM DUAL UNION ALL
    SELECT 12000005, 'CREATE CITY' FROM DUAL UNION ALL
    SELECT 12000006, 'CREATE AIRPORT' FROM DUAL UNION ALL
    SELECT 12000007, 'CREATE FLIGHT COMPANY' FROM DUAL UNION ALL
    SELECT 12000008, 'CREATE FLIGHT' FROM DUAL UNION ALL
    SELECT 12000009, 'REGISTER CUSTOMER' FROM DUAL UNION ALL
    SELECT 12000010, 'SEAT BOOKING' FROM DUAL UNION ALL
    SELECT 12000011, 'CREATE DYNAMIC PRICE' FROM DUAL
) source ON (target.MENU_NAME = source.MENU_NAME)
WHEN NOT MATCHED THEN
    INSERT (MENU_ID, MENU_NAME, IS_ACTIVE, CREATED_BY, CREATED_IP)
    VALUES (source.MENU_ID, source.MENU_NAME, 'Y', 'SYSTEM', '127.0.0.1');

COMMIT;
